// SINGLE SOURCE for requirement IDs. Generates docs/requirements/REQUIREMENTS.md and TRACEABILITY_MATRIX.md.
// FR rows are mapped to API endpoints via `reqs: [...]` in endpoints.mjs; `ui: true` = UI-only (no endpoint of its own).
// Priority: MUST = core demo | SHOULD = important, may be simplified | NICE = only if time remains. (Nothing is removed; see ASSUMPTIONS A-30.)
// Scene = where the problem statement (PDF) demands it.

export const MODULES = {
  AUTH: 'Authentication & access', PUB: 'Public website', MEM: 'Membership', COURT: 'Court booking', SOC: 'Social play', SHOP: 'Shop',
  INV: 'Inventory', BAR: 'Bar / POS', KIT: 'Kitchen orders', ENQ: 'Enquiries / CRM', FIN: 'Finance & payments', INVC: 'Business clients & invoicing',
  STAFF: 'Staff / HR', REP: 'Reporting', NOTIF: 'Notifications', SET: 'Club settings',
};

// [id, priority, actors, text, scene, extras]
export const FR = [
  // ---- AUTH
  ['FR-AUTH-001', 'MUST', 'Visitor', 'A visitor can sign up; the new account is a MEMBER with no plan yet (walk-in rates until a plan is bought).', 'Public website / signup'],
  ['FR-AUTH-002', 'MUST', 'All', 'One login for everyone; after authentication the user lands on the dashboard of their role (redirect_to).', 'Auth flow'],
  ['FR-AUTH-003', 'MUST', 'Visitor', 'Unauthenticated visitors stay on the public website; private routes and APIs answer AUTH_UNAUTHORIZED.', 'Auth flow'],
  ['FR-AUTH-004', 'SHOULD', 'All', 'Users can log out.', 'Auth flow'],
  ['FR-AUTH-005', 'MUST', 'All', 'Every endpoint enforces the role/ownership rules of the permissions matrix server-side (UI hiding is not security).', 'Roles', { ui: true, module: 'AUTH' }],
  ['FR-AUTH-006', 'SHOULD', 'All', 'Users can change their password; accounts created by staff must change it on first login.', 'Auth flow'],
  ['FR-AUTH-007', 'MUST', 'Owner', 'The owner creates accounts for front-desk staff, kitchen manager and business clients.', 'Roles'],
  // ---- PUB
  ['FR-PUB-001', 'MUST', 'Visitor', 'Homepage presents the club: introduction, sports/courts, timings, location and contact.', 'A stranger finds the club online'],
  ['FR-PUB-002', 'MUST', 'Visitor', 'Public membership plans page with Gold / Silver / Junior pricing and benefits.', 'A stranger finds the club online'],
  ['FR-PUB-003', 'MUST', 'Visitor', 'Public court list and availability for the week.', 'A stranger finds the club online ("what is free this week")'],
  ['FR-PUB-004', 'MUST', 'Visitor', 'Public shop catalogue with prices and stock status.', 'A stranger finds the club online ("what the shop sells")'],
  ['FR-PUB-005', 'SHOULD', 'Visitor', 'Public bar & cafeteria menu.', 'Homepage requirement (bar information)'],
  ['FR-PUB-006', 'MUST', 'Visitor', 'Visitor can submit an enquiry or request a trial session without logging in.', 'A stranger finds the club online ("book a trial session")'],
  ['FR-PUB-007', 'MUST', 'Visitor', 'Login and signup entry points on every public page.', 'Homepage requirement', { ui: true, module: 'PUB' }],
  ['FR-PUB-008', 'SHOULD', 'Visitor', 'Upcoming Friday social-play sessions are visible publicly.', 'Booking a court on a busy evening (Friday social play)'],
  // ---- MEM
  ['FR-MEM-001', 'MUST', 'Front desk', 'Front desk registers a new member (identity + plan) in one flow.', 'A new member walks in'],
  ['FR-MEM-002', 'MUST', 'Front desk', 'Any staff member can find a member quickly by name, phone, email or member code.', 'A new member walks in ("recognise them quickly")'],
  ['FR-MEM-003', 'MUST', 'Front desk, Member', 'View a member profile: plan, what it entitles them to, expiry.', 'A new member walks in ("what that plan entitles them to")'],
  ['FR-MEM-004', 'MUST', 'Front desk, Member', 'View a member\'s history with the club (membership terms, bookings, orders, payments).', 'A new member walks in ("see their history with the club")'],
  ['FR-MEM-005', 'MUST', 'All', 'Memberships have an expiry date; status and days remaining are always visible.', 'A new member walks in ("membership will run out one day")'],
  ['FR-MEM-006', 'MUST', 'Front desk, Owner', 'List of memberships about to expire.', 'A new member walks in ("nobody should have to remember when")'],
  ['FR-MEM-007', 'MUST', 'Member, Front desk', 'Buy or renew a membership with payment recorded.', 'A new member walks in'],
  ['FR-MEM-008', 'MUST', 'Front desk', 'Change a member\'s plan (upgrade/downgrade) with history preserved.', 'Booking a court ("Plans change")'],
  ['FR-MEM-009', 'SHOULD', 'Owner', 'Cancel a membership.', 'Implied by membership lifecycle'],
  ['FR-MEM-010', 'SHOULD', 'System', 'Automatic expiry warning and expired notifications; expiry job keeps statuses correct.', 'A new member walks in ("nobody should have to remember when")'],
  ['FR-MEM-011', 'MUST', 'Owner', 'Plan benefits (price, discounts, plays/day) are data, editable by the owner; no plan logic hardcoded in the UI.', 'A new member walks in ("from court rates to discounts at the shop and the bar")'],
  ['FR-MEM-012', 'MUST', 'System', 'Junior plan is only available to members under 18.', 'Club description (Junior = under 18)'],
  ['FR-MEM-013', 'SHOULD', 'Member', 'A member can edit their own profile.', 'Member dashboard'],
  ['FR-MEM-014', 'SHOULD', 'Owner', 'Owner sees members by type, new registrations and membership revenue.', 'The owner at the end of the month'],
  ['FR-MEM-015', 'NICE', 'Front desk', 'Member photo shown at the desk for quick recognition (photo_url stored; upload UI optional).', 'A new member walks in ("recognise them quickly")', { ui: true, module: 'MEM' }],
  // ---- COURT
  ['FR-COURT-001', 'MUST', 'Visitor, Member, Staff', 'View courts with sport, surface and rate.', 'Club description'],
  ['FR-COURT-002', 'MUST', 'Visitor, Member, Staff', 'Live availability grid per court and date (replaces phone calls).', 'Booking a court on a busy evening ("what is free")'],
  ['FR-COURT-003', 'MUST', 'System', 'Sessions last 1 hour; a new slot starts every 30 minutes within opening hours.', 'Booking a court on a busy evening'],
  ['FR-COURT-004', 'MUST', 'Member', 'A member books a court for themselves.', 'Booking a court on a busy evening'],
  ['FR-COURT-005', 'MUST', 'Front desk', 'Front desk books for a member (counter or phone).', 'Booking a court on a busy evening'],
  ['FR-COURT-006', 'MUST', 'Front desk', 'Front desk books for a walk-in guest.', 'Booking a court on a busy evening ("a walk-in is standing at the counter")'],
  ['FR-COURT-007', 'MUST', 'System', 'Price depends on who plays: walk-in rate, member discount per plan, free when the plan gives 100%; expired/no plan pays walk-in rate.', 'Booking a court ("Members pay less than walk-ins, or nothing at all")'],
  ['FR-COURT-008', 'MUST', 'System', 'A member can play at most 2 times per day (plan.max_plays_per_day).', 'Booking a court ("at most twice a day")'],
  ['FR-COURT-009', 'MUST', 'System', 'Two bookings can never overlap on the same court (guaranteed by the database).', 'Booking a court ("never end up on the same court at the same time")'],
  ['FR-COURT-010', 'MUST', 'Member, Front desk', 'Cancel a booking; slot is released; refund per cut-off policy.', 'Booking a court ("people cancel")'],
  ['FR-COURT-011', 'MUST', 'Member', 'A member sees their upcoming and past bookings.', 'Member dashboard'],
  ['FR-COURT-012', 'SHOULD', 'Member, Front desk', 'Price preview before confirming a booking.', 'Booking a court'],
  ['FR-COURT-013', 'SHOULD', 'Owner', 'Block courts for maintenance.', 'Implied by availability management'],
  ['FR-COURT-014', 'SHOULD', 'Front desk', 'Mark a booking completed.', 'Booking lifecycle'],
  ['FR-COURT-015', 'MUST', 'Owner', 'Manage the court catalogue (add, edit, change rates, deactivate).', 'Club description'],
  ['FR-COURT-016', 'MUST', 'Front desk, Owner', 'Day/week view of all bookings for the desk.', 'Booking a court on a busy evening'],
  // ---- SOC
  ['FR-SOC-001', 'MUST', 'Front desk, Owner', 'Open courts for Friday social play (multiple people share a court).', 'Booking a court ("on Friday night the courts open up for social play")'],
  ['FR-SOC-002', 'MUST', 'Visitor, Member, Front desk', 'List upcoming social sessions with spots left.', 'Booking a court (Friday social play)'],
  ['FR-SOC-003', 'MUST', 'Member, Front desk', 'Join a social session (member or guest), paying a per-person fee.', 'Booking a court ("many people share one court")'],
  ['FR-SOC-004', 'MUST', 'Member, Front desk', 'Leave a social session.', 'Booking a court ("people cancel")'],
  ['FR-SOC-005', 'MUST', 'System', 'Session capacity is enforced and the session holds the court so it cannot be double-booked.', 'Booking a court ("never ... same court at the same time")'],
  ['FR-SOC-006', 'SHOULD', 'Front desk, Owner', 'Cancel a whole session and refund participants.', 'Social play lifecycle'],
  ['FR-SOC-007', 'MUST', 'System', 'Social participation counts toward the member\'s daily plays limit.', 'Booking a court ("at most twice a day") — see ASSUMPTIONS A-12'],
  // ---- SHOP
  ['FR-SHOP-001', 'MUST', 'Visitor, Member', 'Browse rackets, balls, shoes, accessories and apparel with stock status.', 'Gearing up before a match'],
  ['FR-SHOP-002', 'MUST', 'Owner', 'Manage products (create, edit, price, retire).', 'Gearing up before a match'],
  ['FR-SHOP-003', 'MUST', 'Front desk', 'Ring up a physical (counter) sale.', 'Gearing up before a match ("what a member buys at the counter")'],
  ['FR-SHOP-004', 'MUST', 'Member', 'Order products online.', 'Gearing up before a match ("order them from home")'],
  ['FR-SHOP-005', 'MUST', 'Member, Front desk', 'Pickup option: order is prepared and collected at the club.', 'Gearing up before a match ("collect them at the club")'],
  ['FR-SHOP-006', 'MUST', 'Member, Front desk', 'Delivery option with address and delivery fee.', 'Gearing up before a match ("have them delivered")'],
  ['FR-SHOP-007', 'MUST', 'System', 'Stock is validated atomically at sale time; overselling is impossible.', 'Gearing up before a match ("always know what is in stock")'],
  ['FR-SHOP-008', 'MUST', 'System', 'Member shop discount is applied automatically from the plan.', 'A new member walks in ("discounts at the shop")'],
  ['FR-SHOP-009', 'MUST', 'Front desk, Owner', 'Track and advance order status through to completion.', 'Gearing up before a match'],
  ['FR-SHOP-010', 'SHOULD', 'Member, Front desk', 'Cancel an order; stock is restored and payment refunded.', 'Order lifecycle'],
  ['FR-SHOP-011', 'MUST', 'Member', 'A member sees their shop orders and status.', 'Member dashboard'],
  // ---- INV
  ['FR-INV-001', 'MUST', 'System', 'Counter and online sales draw from the same stock ("same shelf").', 'Gearing up before a match ("come from the same shelf")'],
  ['FR-INV-002', 'MUST', 'Front desk, Owner', 'Low-stock products are detectable at a glance.', 'Gearing up before a match ("when something is running low")'],
  ['FR-INV-003', 'MUST', 'Owner', 'Restock and correct stock; every change is recorded.', 'Gearing up before a match'],
  ['FR-INV-004', 'SHOULD', 'Owner', 'Stock movement history per product.', 'Inventory control'],
  ['FR-INV-005', 'SHOULD', 'System', 'Low-stock notifications to the owner.', 'Gearing up before a match ("when something is running low")'],
  // ---- BAR
  ['FR-BAR-001', 'MUST', 'Visitor, Member', 'Bar & cafeteria menu.', 'After the match, at the bar'],
  ['FR-BAR-002', 'MUST', 'Front desk, Owner', 'Tables are tracked with live status.', 'After the match ("tables need to be tracked")'],
  ['FR-BAR-003', 'MUST', 'Front desk', 'Take an order for a table / member / guest; it reaches the kitchen instantly.', 'After the match ("Orders are scribbled on paper")'],
  ['FR-BAR-004', 'MUST', 'System', 'Members get their bar discount automatically, without asking.', 'After the match ("Members expect their discount without having to ask")'],
  ['FR-BAR-005', 'MUST', 'System', 'Guests pay list price.', 'After the match ("Guests pay")'],
  ['FR-BAR-006', 'MUST', 'Front desk', 'Open a tab for a member or guest.', 'After the match ("run a tab")'],
  ['FR-BAR-007', 'MUST', 'Front desk', 'Settle a tab before the customer leaves.', 'After the match ("settle up before they leave")'],
  ['FR-BAR-008', 'MUST', 'Front desk', 'Accept cash, card or UPI.', 'After the match ("cash, card or UPI")'],
  ['FR-BAR-009', 'MUST', 'Front desk, Owner', 'Daily bar revenue available at closing time.', 'After the match ("what the bar actually earned that day")'],
  ['FR-BAR-010', 'SHOULD', 'Front desk', 'Cancel a bar order before it is prepared.', 'Order lifecycle'],
  ['FR-BAR-011', 'MUST', 'Owner', 'Manage the bar menu and availability.', 'After the match'],
  ['FR-BAR-012', 'SHOULD', 'Member', 'A member sees their bar orders and tabs.', 'Member dashboard (bar activity)'],
  ['FR-BAR-013', 'MUST', 'System', 'Orders and tabs are stored digitally; a tab cannot be lost.', 'After the match ("tabs get lost")'],
  // ---- KIT
  ['FR-KIT-001', 'MUST', 'Kitchen manager', 'See incoming orders on a live board.', 'After the match ("the kitchen keeps asking who ordered what")'],
  ['FR-KIT-002', 'MUST', 'Kitchen manager', 'Each order shows items, quantities, table/tab and who ordered.', 'After the match ("who ordered what")'],
  ['FR-KIT-003', 'MUST', 'Kitchen manager', 'Progress an order NEW → ACCEPTED → PREPARING → READY → SERVED.', 'Kitchen flow'],
  ['FR-KIT-004', 'MUST', 'Kitchen manager', 'The kitchen view exposes no financial, inventory, HR or admin data.', 'Role definition (Kitchen Manager kept simple)'],
  ['FR-KIT-005', 'SHOULD', 'Kitchen manager', 'Reject/cancel NEW or ACCEPTED orders with a reason.', 'Kitchen flow'],
  ['FR-KIT-006', 'SHOULD', 'Front desk', 'Staff are notified when an order is READY.', 'Kitchen flow'],
  // ---- ENQ
  ['FR-ENQ-001', 'MUST', 'Visitor, Front desk', 'Enquiries are stored and never vanish.', 'A stranger finds the club online ("that enquiry should not vanish")'],
  ['FR-ENQ-002', 'MUST', 'Visitor', 'Visitors can request a trial session.', 'A stranger finds the club online ("book a trial session")'],
  ['FR-ENQ-003', 'MUST', 'Front desk', 'Staff log phone and walk-in enquiries.', 'Front desk handles walk-ins, phone calls'],
  ['FR-ENQ-004', 'MUST', 'Front desk, Owner', 'List and filter enquiries by status, type and assignee.', 'A stranger finds the club online'],
  ['FR-ENQ-005', 'MUST', 'Front desk, Owner', 'Log follow-ups and schedule the next one.', 'A stranger finds the club online ("follow up")'],
  ['FR-ENQ-006', 'MUST', 'Front desk, Owner', 'Send a quote for a plan.', 'A stranger finds the club online ("send a quote")'],
  ['FR-ENQ-007', 'MUST', 'Front desk, Owner', 'Convert an enquiry into a member.', 'A stranger finds the club online ("welcome a new member")'],
  ['FR-ENQ-008', 'MUST', 'System', 'Staff are notified of a new enquiry.', 'A stranger finds the club online ("Someone at the club should hear about it")'],
  ['FR-ENQ-009', 'SHOULD', 'Front desk', 'Book the trial session on a court for an enquiry.', 'A stranger finds the club online'],
  ['FR-ENQ-010', 'SHOULD', 'Owner, Front desk', 'Funnel summary: new, contacted, quoted, converted, lost.', 'The owner at the end of the month'],
  // ---- FIN
  ['FR-FIN-001', 'MUST', 'Front desk, Member, Owner', 'Record a payment against any billable item (booking, social spot, membership, shop order, bar order, tab, invoice).', 'The owner ("none of it is in one place")'],
  ['FR-FIN-002', 'MUST', 'All', 'Supported methods: cash, card, UPI, online.', 'The owner ("by card, cash and online")'],
  ['FR-FIN-003', 'MUST', 'Owner', 'Revenue by stream (courts, membership, shop, bar, business) in one place.', 'The owner ("how much did we earn, from where")'],
  ['FR-FIN-004', 'MUST', 'Member, Business client', 'Receipts and payment history.', 'Member dashboard'],
  ['FR-FIN-005', 'SHOULD', 'Owner', 'Refunds (full/partial) recorded against the payment.', 'Booking a court ("people cancel")'],
  ['FR-FIN-006', 'MUST', 'Owner', 'Outstanding amounts: unpaid and overdue invoices.', 'The owner ("what do we owe" / invoices)'],
  ['FR-FIN-007', 'MUST', 'Owner', 'Taxes collected are tracked per revenue category.', 'The owner ("taxes to report")'],
  ['FR-FIN-008', 'MUST', 'Owner', 'Employee payments (salary) recorded and pending amounts visible.', 'The owner ("employees to pay")'],
  ['FR-FIN-009', 'MUST', 'Owner', 'Finance overview for today, this week and this month.', 'The owner ("today, this week and this month")'],
  ['FR-FIN-010', 'SHOULD', 'Member, Business client', 'Pay online (mock gateway in the hackathon build).', 'The owner ("online")'],
  // ---- INVC
  ['FR-INVC-001', 'MUST', 'Owner', 'Manage business clients.', 'The owner ("business clients to invoice")'],
  ['FR-INVC-002', 'MUST', 'Owner', 'Create invoices with line items and tax.', 'The owner ("business clients to invoice")'],
  ['FR-INVC-003', 'MUST', 'Owner', 'Send/issue an invoice; the client is notified.', 'The owner ("business clients to invoice")'],
  ['FR-INVC-004', 'MUST', 'Business client, Owner', 'Pay an invoice (partial payments allowed).', 'The owner ("business clients to invoice")'],
  ['FR-INVC-005', 'MUST', 'Business client', 'Transaction history: invoices and payments.', 'Business client flow'],
  ['FR-INVC-006', 'SHOULD', 'Owner', 'Invoice memberships.', 'The owner ("memberships ... to invoice")'],
  ['FR-INVC-007', 'SHOULD', 'Owner', 'Void an unpaid invoice.', 'Invoice lifecycle'],
  ['FR-INVC-008', 'MUST', 'Business client', 'Business dashboard: totals, outstanding, recent invoices.', 'Business client flow'],
  ['FR-INVC-009', 'SHOULD', 'System', 'Overdue invoices are detected automatically.', 'The owner ("what do we owe" / collect)'],
  // ---- STAFF
  ['FR-STAFF-001', 'MUST', 'Owner', 'Staff records.', 'The owner ("employees")'],
  ['FR-STAFF-002', 'MUST', 'Owner', 'Create and edit shift schedules.', 'After the match ("Staff work in shifts")'],
  ['FR-STAFF-003', 'MUST', 'Front desk, Kitchen manager', 'Request leave.', 'The owner ("leave to approve")'],
  ['FR-STAFF-004', 'MUST', 'Owner', 'Approve or reject leave.', 'The owner ("leave to approve")'],
  ['FR-STAFF-005', 'SHOULD', 'Front desk', 'Front desk can view the staff schedule.', 'Club description ("front desk handles ... staff schedules")'],
  ['FR-STAFF-006', 'MUST', 'Owner', 'Payroll records per employee per month.', 'The owner ("employees to pay")'],
  ['FR-STAFF-007', 'SHOULD', 'Front desk, Kitchen manager', 'Staff see their own shifts and payroll history.', 'Staff self-service'],
  // ---- REP
  ['FR-REP-001', 'MUST', 'Owner', 'Dashboard for today / this week / this month.', 'The owner ("today, this week and this month")'],
  ['FR-REP-002', 'MUST', 'Owner', 'Revenue report by day, category, method.', 'The owner ("how much did we earn, from where")'],
  ['FR-REP-003', 'SHOULD', 'Owner', 'Court utilisation and cancellations.', 'The owner ("revenue and operations: no visibility")'],
  ['FR-REP-004', 'SHOULD', 'Owner', 'Membership report: active by type, new, renewals, expiring.', 'The owner'],
  ['FR-REP-005', 'SHOULD', 'Owner', 'Shop sales, top products, low stock.', 'The owner'],
  ['FR-REP-006', 'MUST', 'Owner', 'Bar revenue per day.', 'After the match ("what the bar actually earned that day")'],
  ['FR-REP-007', 'MUST', 'Owner', 'Tax report.', 'The owner ("taxes to report")'],
  ['FR-REP-008', 'SHOULD', 'Owner', 'Export/share the numbers (CSV).', 'The owner ("share the numbers when needed")'],
  ['FR-REP-009', 'MUST', 'Owner', 'Finance report: in, out, owed, tax.', 'The owner ("what do we owe")'],
  // ---- NOTIF / SET
  ['FR-NOTIF-001', 'SHOULD', 'All', 'In-app notifications list with unread badge.', 'Cross-cutting (expiry, orders, enquiries...)'],
  ['FR-NOTIF-002', 'SHOULD', 'All', 'Mark notifications as read.', 'Cross-cutting'],
  ['FR-NOTIF-003', 'SHOULD', 'System', 'Notifications are created by business events (expiry, booking, order ready, low stock, enquiry, leave, invoice).', 'Cross-cutting'],
  ['FR-SET-001', 'MUST', 'Owner', 'Owner edits club settings (hours, tax rates, delivery fee, cut-offs, social-play window).', 'Avoids hardcoded policy'],
];

// [id, priority, text, how verified]
export const NFR = [
  ['NFR-UX-001', 'MUST', 'Responsive web UI usable on phone (375px) and desktop; front desk and kitchen screens optimised for tablet/desktop.'],
  ['NFR-UX-002', 'SHOULD', 'Every screen has loading, empty and error states; errors show the API message for the error code.'],
  ['NFR-UX-003', 'SHOULD', 'Basic accessibility: labelled inputs, keyboard focus, AA colour contrast.'],
  ['NFR-SEC-001', 'MUST', 'Passwords stored as bcrypt hashes; API returns UserPublic only; JWT expires (8 h).'],
  ['NFR-SEC-002', 'MUST', 'Authorisation enforced server-side per PERMISSIONS_MATRIX; "own" rules enforced in queries, not in the UI.'],
  ['NFR-SEC-003', 'MUST', 'No secrets in git; only .env.example is committed; service-role key is backend-only.'],
  ['NFR-SEC-004', 'MUST', 'Supabase tables have RLS enabled with no policies; only the backend (DATABASE_URL) can read/write.'],
  ['NFR-SEC-005', 'SHOULD', 'Input validated at the API boundary (shape, ranges, enums); parameterised SQL only.'],
  ['NFR-PERF-001', 'SHOULD', 'List and dashboard endpoints respond < 500 ms and availability < 1 s at demo data volume.'],
  ['NFR-REL-001', 'MUST', 'Multi-table writes (booking+payment, order+stock+payment, tab settlement, conversion) run in one DB transaction.'],
  ['NFR-REL-002', 'MUST', 'Double-booking, negative stock, two active memberships and one-active-tab rules are enforced by the database, not only by code.'],
  ['NFR-REL-003', 'MUST', 'Financial rows are never hard-deleted; refunds and cancellations are new state, not deletions.'],
  ['NFR-MNT-001', 'MUST', 'Frontend and backend import types/enums/errors from /shared; no local copies.'],
  ['NFR-MNT-002', 'MUST', 'Code organised by module with the ownership boundaries in TEAM_GUIDELINES.md.'],
  ['NFR-CON-001', 'MUST', 'Date/time, money, id, response and error formats follow docs/contracts/CONVENTIONS (SHARED_TYPES.md).'],
  ['NFR-DEMO-001', 'MUST', 'One command resets and seeds a demo database; seed data exercises every role and every key rule.'],
  ['NFR-OBS-001', 'NICE', 'Request logging with a request id; errors logged with stack traces server-side only.'],
  ['NFR-TEST-001', 'SHOULD', 'Automated tests for the critical rules: double-booking, daily limit, stock oversell, tab settlement, payment totals.'],
];

// Covers lists map user / business requirements onto FRs (so the traceability matrix is complete for every ID).
export const UR = [
  ['UR-VIS-001', 'MUST', 'Visitor', 'As an online visitor I can see the club, plans and prices, what is free this week and what the shop sells, and request a trial or enquire — without an account.', ['FR-PUB-001', 'FR-PUB-002', 'FR-PUB-003', 'FR-PUB-004', 'FR-PUB-005', 'FR-PUB-006', 'FR-PUB-007', 'FR-PUB-008', 'FR-ENQ-001', 'FR-ENQ-002']],
  ['UR-VIS-002', 'MUST', 'Visitor', 'As a visitor I can sign up and log in.', ['FR-AUTH-001', 'FR-AUTH-002', 'FR-AUTH-003']],
  ['UR-MEM-001', 'MUST', 'Member', 'As a member I can see my profile, plan, benefits, expiry and history.', ['FR-MEM-003', 'FR-MEM-004', 'FR-MEM-005', 'FR-MEM-013']],
  ['UR-MEM-002', 'MUST', 'Member', 'As a member I can check availability, book and cancel courts, and see my bookings.', ['FR-COURT-002', 'FR-COURT-004', 'FR-COURT-010', 'FR-COURT-011', 'FR-COURT-012']],
  ['UR-MEM-003', 'MUST', 'Member', 'As a member I can join Friday social play.', ['FR-SOC-002', 'FR-SOC-003', 'FR-SOC-004']],
  ['UR-MEM-004', 'MUST', 'Member', 'As a member I can order gear online for pickup or delivery and track it.', ['FR-SHOP-001', 'FR-SHOP-004', 'FR-SHOP-005', 'FR-SHOP-006', 'FR-SHOP-011']],
  ['UR-MEM-005', 'SHOULD', 'Member', 'As a member I see my discounts, bar activity, payments and receipts, and can renew my plan.', ['FR-SHOP-008', 'FR-BAR-004', 'FR-BAR-012', 'FR-FIN-004', 'FR-MEM-007']],
  ['UR-GST-001', 'MUST', 'Walk-in guest', 'As a walk-in guest I am served by staff: book a court, join social play, buy gear, order food and pay by cash/card/UPI without an account.', ['FR-COURT-006', 'FR-SOC-003', 'FR-SHOP-003', 'FR-BAR-003', 'FR-BAR-005', 'FR-BAR-008']],
  ['UR-FD-001', 'MUST', 'Front desk', 'As front desk I register and find members, see their plan, expiry and history in seconds.', ['FR-MEM-001', 'FR-MEM-002', 'FR-MEM-003', 'FR-MEM-004', 'FR-MEM-005', 'FR-MEM-006']],
  ['UR-FD-002', 'MUST', 'Front desk', 'As front desk I manage court bookings for members, walk-ins and phone callers, and cancellations.', ['FR-COURT-005', 'FR-COURT-006', 'FR-COURT-010', 'FR-COURT-016', 'FR-SOC-001']],
  ['UR-FD-003', 'MUST', 'Front desk', 'As front desk I handle enquiries, trials, follow-ups and quotes.', ['FR-ENQ-003', 'FR-ENQ-004', 'FR-ENQ-005', 'FR-ENQ-006', 'FR-ENQ-007', 'FR-ENQ-009']],
  ['UR-FD-004', 'MUST', 'Front desk', 'As front desk I run the bar/shop counter: orders, tabs, payments.', ['FR-SHOP-003', 'FR-BAR-002', 'FR-BAR-003', 'FR-BAR-006', 'FR-BAR-007', 'FR-BAR-008']],
  ['UR-KIT-001', 'MUST', 'Kitchen manager', 'As kitchen manager I see incoming orders by table and move them to served — nothing else.', ['FR-KIT-001', 'FR-KIT-002', 'FR-KIT-003', 'FR-KIT-004', 'FR-KIT-005']],
  ['UR-BC-001', 'MUST', 'Business client', 'As a business client I see my invoices, pay them and see my transaction history.', ['FR-INVC-004', 'FR-INVC-005', 'FR-INVC-008', 'FR-FIN-010']],
  ['UR-OWN-001', 'MUST', 'Owner', 'As owner I see how the club is doing today, this week and this month across every stream.', ['FR-REP-001', 'FR-REP-002', 'FR-FIN-003', 'FR-FIN-009']],
  ['UR-OWN-002', 'MUST', 'Owner', 'As owner I control membership plans, courts, products, stock and the bar menu.', ['FR-MEM-011', 'FR-COURT-015', 'FR-SHOP-002', 'FR-INV-003', 'FR-BAR-011', 'FR-SET-001']],
  ['UR-OWN-003', 'MUST', 'Owner', 'As owner I invoice business clients, track what is owed, pay employees and approve leave.', ['FR-INVC-001', 'FR-INVC-002', 'FR-INVC-003', 'FR-FIN-006', 'FR-FIN-008', 'FR-STAFF-004', 'FR-STAFF-006']],
  ['UR-OWN-004', 'MUST', 'Owner', 'As owner I can see taxes and share the numbers.', ['FR-FIN-007', 'FR-REP-007', 'FR-REP-008']],
];

export const BR = [
  ['BR-001', 'MUST', 'Replace WhatsApp bookings, Excel member lists, paper receipts and phone availability checks with one platform.', ['FR-COURT-002', 'FR-COURT-004', 'FR-MEM-001', 'FR-BAR-013', 'FR-PUB-003']],
  ['BR-002', 'MUST', 'Eliminate double bookings and enforce the plays-per-day limit.', ['FR-COURT-008', 'FR-COURT-009', 'FR-SOC-005']],
  ['BR-003', 'MUST', 'Make membership lifecycle automatic: expiry visible, renewals prompted, benefits applied by plan.', ['FR-MEM-005', 'FR-MEM-006', 'FR-MEM-010', 'FR-MEM-011']],
  ['BR-004', 'MUST', 'Know stock at all times across counter and online; never oversell; spot low stock.', ['FR-INV-001', 'FR-INV-002', 'FR-SHOP-007']],
  ['BR-005', 'MUST', 'Speed up bar service: no lost orders or tabs, kitchen knows who ordered what, members get discounts automatically.', ['FR-BAR-003', 'FR-BAR-004', 'FR-BAR-006', 'FR-BAR-007', 'FR-KIT-001']],
  ['BR-006', 'MUST', 'Turn online visitors into members: capture, follow up, quote, convert.', ['FR-ENQ-001', 'FR-ENQ-005', 'FR-ENQ-006', 'FR-ENQ-007']],
  ['BR-007', 'MUST', 'Give the owner one trustworthy view of income by stream and payment method.', ['FR-FIN-001', 'FR-FIN-003', 'FR-REP-001']],
  ['BR-008', 'MUST', 'Collect what is owed: invoice business clients and memberships, chase overdue amounts.', ['FR-INVC-002', 'FR-FIN-006', 'FR-INVC-009']],
  ['BR-009', 'MUST', 'Run the workforce: shifts, leave approval, payroll.', ['FR-STAFF-002', 'FR-STAFF-004', 'FR-STAFF-006']],
  ['BR-010', 'MUST', 'Support tax reporting.', ['FR-FIN-007', 'FR-REP-007']],
  ['BR-011', 'SHOULD', 'Let the owner share numbers with partners/accountants.', ['FR-REP-008']],
];

// Problem-statement coverage: every capability named in the brief -> the requirement IDs that deliver it.
export const COVERAGE = [
  ['Roles: Member (Gold/Silver/Junior), Front Desk, Kitchen Manager, Business Client, Owner/Admin', ['FR-AUTH-002', 'FR-AUTH-005', 'FR-AUTH-007']],
  ['Courts catalogue (tennis, cricket, padel, badminton)', ['FR-COURT-001', 'FR-COURT-015']],
  ['Shop order tracking (placed → ready/out for delivery → completed)', ['FR-SHOP-009']],
  ['Bar & cafeteria menu', ['FR-BAR-001', 'FR-BAR-011']],
  ['Employee records', ['FR-STAFF-001']],
  ['Owner overview of money in, owed and taxes', ['FR-REP-009']],
  ['Gold / Silver / Junior memberships', ['FR-MEM-011', 'FR-PUB-002', 'FR-MEM-012']],
  ['Membership benefits (court rates, shop and bar discounts)', ['FR-MEM-003', 'FR-MEM-011', 'FR-COURT-007', 'FR-SHOP-008', 'FR-BAR-004']],
  ['Membership expiry (nobody has to remember)', ['FR-MEM-005', 'FR-MEM-006', 'FR-MEM-010']],
  ['Recognise a member quickly and see their history', ['FR-MEM-002', 'FR-MEM-004']],
  ['Plan changes', ['FR-MEM-008']],
  ['Court availability without phone calls', ['FR-COURT-002', 'FR-PUB-003']],
  ['1-hour sessions, new slot every 30 minutes', ['FR-COURT-003']],
  ['Maximum 2 plays per member per day', ['FR-COURT-008', 'FR-SOC-007']],
  ['Member vs walk-in pricing; free access by plan', ['FR-COURT-007']],
  ['Cancellations', ['FR-COURT-010', 'FR-SOC-004', 'FR-SOC-006']],
  ['Friday social play with many people on one court', ['FR-SOC-001', 'FR-SOC-002', 'FR-SOC-003', 'FR-SOC-005']],
  ['Two people never on the same court at the same time', ['FR-COURT-009', 'FR-SOC-005']],
  ['Shop: rackets, balls, shoes, accessories, apparel', ['FR-SHOP-001', 'FR-SHOP-002']],
  ['Inventory, stock levels and low-stock tracking', ['FR-INV-001', 'FR-INV-002', 'FR-INV-003', 'FR-INV-005']],
  ['Physical (counter) sales and online orders from the same shelf', ['FR-SHOP-003', 'FR-SHOP-004', 'FR-INV-001', 'FR-SHOP-007']],
  ['Pickup and delivery', ['FR-SHOP-005', 'FR-SHOP-006']],
  ['Bar orders, tables, kitchen handling', ['FR-BAR-002', 'FR-BAR-003', 'FR-KIT-001', 'FR-KIT-002', 'FR-KIT-003']],
  ['Member bar discount without asking; guests pay list price', ['FR-BAR-004', 'FR-BAR-005']],
  ['Tabs: run a tab and settle before leaving', ['FR-BAR-006', 'FR-BAR-007']],
  ['Cash, card, UPI payments', ['FR-BAR-008', 'FR-FIN-002']],
  ['Staff shifts', ['FR-STAFF-002', 'FR-STAFF-005']],
  ['Daily bar revenue at closing', ['FR-BAR-009', 'FR-REP-006']],
  ['Public website: club, plans and prices, availability, shop', ['FR-PUB-001', 'FR-PUB-002', 'FR-PUB-003', 'FR-PUB-004', 'FR-PUB-005']],
  ['Trial sessions', ['FR-ENQ-002', 'FR-ENQ-009']],
  ['Enquiries that never vanish, follow-ups, quotes, conversion', ['FR-ENQ-001', 'FR-ENQ-004', 'FR-ENQ-005', 'FR-ENQ-006', 'FR-ENQ-007', 'FR-ENQ-008']],
  ['Front desk: register/search members, walk-ins, phone enquiries, schedules', ['FR-MEM-001', 'FR-MEM-002', 'FR-COURT-006', 'FR-ENQ-003', 'FR-STAFF-005']],
  ['Revenue from courts, shop, bar (and memberships) in one place', ['FR-FIN-003', 'FR-REP-002']],
  ['Money by card, cash and online', ['FR-FIN-002', 'FR-FIN-010']],
  ['Memberships and business clients to invoice', ['FR-INVC-001', 'FR-INVC-002', 'FR-INVC-003', 'FR-INVC-004', 'FR-INVC-006']],
  ['What do we owe / outstanding amounts', ['FR-FIN-006', 'FR-INVC-009']],
  ['Employees to pay; leave to approve', ['FR-FIN-008', 'FR-STAFF-006', 'FR-STAFF-003', 'FR-STAFF-004']],
  ['Taxes to report', ['FR-FIN-007', 'FR-REP-007']],
  ['Today / this week / this month; share the numbers', ['FR-REP-001', 'FR-FIN-009', 'FR-REP-008']],
];
