/**
 * GENERATED by tools/gen-docs.mjs from tools/api/endpoints.mjs — DO NOT EDIT BY HAND.
 * One interface per endpoint body (…Request) / query string (…Query). Frontend sends these; backend validates against them.
 * Query-string values arrive as strings on the wire and are coerced by the validator to the types below.
 */
import type * as E from '../constants/enums';
import type { Uuid, Money, Percent, IsoDate, IsoDateTime, TimeOfDay } from './rows';

/** POST /api/v1/auth/signup (auth.signup) */
export interface AuthSignupRequest {
  full_name: string; // 2-120 chars
  email: string; // unique (case-insensitive)
  phone: string;
  password: string; // min 8 chars, >=1 letter and >=1 digit
  date_of_birth?: IsoDate; // must be in the past
}

/** POST /api/v1/auth/login (auth.login) */
export interface AuthLoginRequest {
  email: string;
  password: string;
}

/** POST /api/v1/auth/change-password (auth.changePassword) */
export interface AuthChangePasswordRequest {
  current_password: string;
  new_password: string; // min 8 chars, >=1 letter and >=1 digit
}

/** GET /api/v1/members (members.list) */
export interface MembersListQuery {
  q?: string; // matches full_name, phone, email, member_code (case-insensitive contains)
  membership_type?: E.MembershipType;
  membership_status?: E.MembershipStatus;
  no_plan?: boolean; // true = members with no current membership
  expiring_within_days?: number; // >=0
}

/** POST /api/v1/members (members.create) */
export interface MembersCreateRequest {
  full_name: string;
  email: string;
  phone: string;
  date_of_birth?: IsoDate; // REQUIRED when membership_plan_id is a JUNIOR plan
  address?: string;
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  initial_password?: string; // if omitted the server generates one; account gets must_change_password = true
  membership_plan_id?: Uuid; // buy this plan now
  payment_method?: E.PaymentMethod; // REQUIRED when membership_plan_id is given
}

/** PATCH /api/v1/members/:id (members.update) */
export interface MembersUpdateRequest {
  full_name?: string;
  phone?: string;
  date_of_birth?: IsoDate;
  address?: string;
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  photo_url?: string;
  notes?: string; // staff only
  is_active?: boolean; // OWNER_ADMIN only
}

/** GET /api/v1/members/:id/history (members.history) */
export interface MembersHistoryQuery {
  event_type?: E.HistoryEventType;
  from?: IsoDate;
  to?: IsoDate;
}

/** GET /api/v1/memberships/plans (memberships.plans) */
export interface MembershipsPlansQuery {
  include_inactive?: boolean; // OWNER_ADMIN only
}

/** POST /api/v1/memberships/plans (memberships.planCreate) */
export interface MembershipsPlanCreateRequest {
  membership_type: E.MembershipType;
  name: string;
  description?: string;
  duration_months: number; // >0
  price: Money;
  court_discount_percent?: Percent; // 0-100; 100 = free courts
  shop_discount_percent?: Percent;
  bar_discount_percent?: Percent;
  max_plays_per_day?: number; // default 2
  min_age?: number;
  max_age?: number;
  benefits?: string[];
  sort_order?: number;
}

/** PATCH /api/v1/memberships/plans/:id (memberships.planUpdate) */
export interface MembershipsPlanUpdateRequest {
  name?: string;
  description?: string;
  price?: Money;
  court_discount_percent?: Percent;
  shop_discount_percent?: Percent;
  bar_discount_percent?: Percent;
  max_plays_per_day?: number;
  benefits?: string[];
  sort_order?: number;
  is_active?: boolean;
}

/** POST /api/v1/memberships (memberships.purchase) */
export interface MembershipsPurchaseRequest {
  member_id?: Uuid; // Staff only; MEMBER callers: implied = self
  membership_plan_id: Uuid;
  payment_method: E.PaymentMethod; // MEMBER callers must use ONLINE
  gateway_reference?: string;
}

/** POST /api/v1/memberships/:id/change-plan (memberships.changePlan) */
export interface MembershipsChangePlanRequest {
  new_membership_plan_id: Uuid;
  payment_method: E.PaymentMethod;
}

/** POST /api/v1/memberships/:id/cancel (memberships.cancel) */
export interface MembershipsCancelRequest {
  reason: string;
}

/** GET /api/v1/memberships/expiring (memberships.expiring) */
export interface MembershipsExpiringQuery {
  days?: number; // 1-365
}

/** GET /api/v1/courts (courts.list) */
export interface CourtsListQuery {
  sport_type?: E.SportType;
  include_inactive?: boolean; // staff only
}

/** GET /api/v1/courts/availability (courts.availability) */
export interface CourtsAvailabilityQuery {
  date: IsoDate; // today .. today+60d (IST)
  sport_type?: E.SportType;
  court_id?: Uuid;
}

/** POST /api/v1/courts (courts.create) */
export interface CourtsCreateRequest {
  name: string; // unique
  sport_type: E.SportType;
  description?: string;
  surface?: string;
  walk_in_rate_per_hour: Money;
  image_url?: string;
  sort_order?: number;
}

/** PATCH /api/v1/courts/:id (courts.update) */
export interface CourtsUpdateRequest {
  name?: string;
  description?: string;
  surface?: string;
  walk_in_rate_per_hour?: Money;
  image_url?: string;
  sort_order?: number;
  is_active?: boolean;
}

/** POST /api/v1/courts/:id/blocks (courts.block) */
export interface CourtsBlockRequest {
  start_at: IsoDateTime; // on a 30-min boundary
  end_at: IsoDateTime; // multiple of 1h after start_at
  reason?: string;
}

/** GET /api/v1/bookings/price (bookings.price) */
export interface BookingsPriceQuery {
  court_id: Uuid;
  start_at: IsoDateTime;
  member_id?: Uuid; // staff only; omit for walk-in pricing
}

/** POST /api/v1/bookings (bookings.create) */
export interface BookingsCreateRequest {
  court_id: Uuid;
  start_at: IsoDateTime; // on a :00/:30 boundary, in the future, session must end by club_close_time
  member_id?: Uuid; // Staff only: book/order on behalf of this member. MEMBER callers: omit (implied = self).
  guest_name?: string; // Walk-in name. Staff only. Required when no member_id.
  guest_phone?: string; // Walk-in phone (E.164 or 10-digit). Staff only.
  payment_method?: E.PaymentMethod; // omit = pay later at the desk (payment_status PENDING). MEMBER callers pay ONLINE or later at desk.
  notes?: string;
}

/** GET /api/v1/bookings (bookings.list) */
export interface BookingsListQuery {
  from?: IsoDate;
  to?: IsoDate;
  court_id?: Uuid;
  member_id?: Uuid; // staff only
  status?: E.BookingStatus;
  booking_type?: E.BookingType;
  upcoming?: boolean; // true = start_at >= now
}

/** POST /api/v1/bookings/:id/cancel (bookings.cancel) */
export interface BookingsCancelRequest {
  reason?: string;
  refund?: boolean; // staff only: override policy (default: refund if start_at - now >= cancellation_cutoff_hours)
}

/** GET /api/v1/social-play/sessions (social.list) */
export interface SocialListQuery {
  from?: IsoDate;
  to?: IsoDate;
  status?: E.SocialSessionStatus;
}

/** POST /api/v1/social-play/sessions (social.create) */
export interface SocialCreateRequest {
  court_id: Uuid;
  start_at: IsoDateTime; // must fall on social_play_weekday (IST) inside the social-play window
  title: string;
  description?: string;
  capacity: number; // >=2
  fee_per_person: Money; // >=0; tax-inclusive guest fee
}

/** POST /api/v1/social-play/sessions/:id/join (social.join) */
export interface SocialJoinRequest {
  member_id?: Uuid; // Staff only: book/order on behalf of this member. MEMBER callers: omit (implied = self).
  guest_name?: string; // Walk-in name. Staff only. Required when no member_id.
  guest_phone?: string; // Walk-in phone (E.164 or 10-digit). Staff only.
  payment_method?: E.PaymentMethod; // omit = pay later at desk
}

/** POST /api/v1/social-play/sessions/:id/leave (social.leave) */
export interface SocialLeaveRequest {
  participant_id?: Uuid; // staff only; required for staff callers
}

/** POST /api/v1/social-play/sessions/:id/cancel (social.cancel) */
export interface SocialCancelRequest {
  reason?: string;
}

/** GET /api/v1/shop/products (shop.products) */
export interface ShopProductsQuery {
  category?: E.ProductCategory;
  q?: string;
  in_stock?: boolean;
  include_inactive?: boolean; // OWNER_ADMIN only
}

/** POST /api/v1/shop/products (shop.productCreate) */
export interface ShopProductCreateRequest {
  sku: string; // unique
  name: string;
  category: E.ProductCategory;
  brand?: string;
  description?: string;
  price: Money; // tax-inclusive
  image_url?: string;
  initial_stock?: number; // >=0; creates an OPENING inventory movement
  low_stock_threshold?: number; // default = setting low_stock_default_threshold
}

/** PATCH /api/v1/shop/products/:id (shop.productUpdate) */
export interface ShopProductUpdateRequest {
  name?: string;
  category?: E.ProductCategory;
  brand?: string;
  description?: string;
  price?: Money;
  image_url?: string;
  low_stock_threshold?: number;
  is_active?: boolean;
}

/** POST /api/v1/shop/orders (shop.orderCreate) */
export interface ShopOrderCreateRequest {
  items: { product_id: Uuid; quantity: number }[]; // 1-50 lines; duplicate products are merged
  fulfillment: E.OrderFulfillment; // MEMBER: PICKUP|DELIVERY. Staff: IN_STORE
  delivery_address?: string; // required when fulfillment = DELIVERY
  member_id?: Uuid; // Staff only: book/order on behalf of this member. MEMBER callers: omit (implied = self).
  guest_name?: string; // Walk-in name. Staff only. Required when no member_id.
  guest_phone?: string; // Walk-in phone (E.164 or 10-digit). Staff only.
  payment_method?: E.PaymentMethod; // MEMBER: ONLINE. Staff counter sale: CASH|CARD|UPI (required for IN_STORE)
  notes?: string;
}

/** GET /api/v1/shop/orders (shop.orderList) */
export interface ShopOrderListQuery {
  status?: E.ShopOrderStatus;
  channel?: E.OrderChannel;
  fulfillment?: E.OrderFulfillment;
  member_id?: Uuid; // staff only
  from?: IsoDate;
  to?: IsoDate;
}

/** PATCH /api/v1/shop/orders/:id/status (shop.orderStatus) */
export interface ShopOrderStatusRequest {
  status: E.ShopOrderStatus; // must be allowed by SHOP_ORDER_TRANSITIONS; READY_FOR_PICKUP only for PICKUP orders, OUT_FOR_DELIVERY only for DELIVERY orders
}

/** POST /api/v1/shop/orders/:id/cancel (shop.orderCancel) */
export interface ShopOrderCancelRequest {
  reason?: string;
}

/** GET /api/v1/inventory (inventory.list) */
export interface InventoryListQuery {
  category?: E.ProductCategory;
  low_stock_only?: boolean;
  q?: string;
}

/** POST /api/v1/inventory/adjustments (inventory.adjust) */
export interface InventoryAdjustRequest {
  product_id: Uuid;
  quantity_change: number; // non-zero; negative allowed only if result stays >= 0 (else VALIDATION_ERROR)
  reason: E.InventoryReason; // RESTOCK | ADJUSTMENT | DAMAGE | RETURN only
  notes?: string;
}

/** GET /api/v1/inventory/movements (inventory.movements) */
export interface InventoryMovementsQuery {
  product_id?: Uuid;
  reason?: E.InventoryReason;
  from?: IsoDate;
  to?: IsoDate;
}

/** GET /api/v1/bar/menu (bar.menu) */
export interface BarMenuQuery {
  category?: E.MenuCategory;
  include_unavailable?: boolean; // staff only
}

/** POST /api/v1/bar/menu-items (bar.menuCreate) */
export interface BarMenuCreateRequest {
  name: string; // unique
  category: E.MenuCategory;
  description?: string;
  price: Money; // tax-inclusive
  sort_order?: number;
}

/** PATCH /api/v1/bar/menu-items/:id (bar.menuUpdate) */
export interface BarMenuUpdateRequest {
  name?: string;
  category?: E.MenuCategory;
  description?: string;
  price?: Money;
  is_available?: boolean;
  sort_order?: number;
}

/** POST /api/v1/bar/tables (bar.tableCreate) */
export interface BarTableCreateRequest {
  label: string; // unique
  capacity: number; // >0
}

/** PATCH /api/v1/bar/tables/:id (bar.tableUpdate) */
export interface BarTableUpdateRequest {
  status?: E.TableStatus;
  label?: string; // OWNER_ADMIN only
  capacity?: number; // OWNER_ADMIN only
}

/** POST /api/v1/bar/orders (bar.orderCreate) */
export interface BarOrderCreateRequest {
  bar_table_id?: Uuid;
  bar_tab_id?: Uuid; // add to an OPEN tab; member/guest then inherited from the tab
  member_id?: Uuid; // Staff only: book/order on behalf of this member. MEMBER callers: omit (implied = self).
  guest_name?: string;
  items: { bar_menu_item_id: Uuid; quantity: number; notes?: string }[]; // 1-50 lines
  payment_method?: E.PaymentMethod; // pay now (CASH|CARD|UPI); omit to leave PENDING or put on a tab
  notes?: string;
}

/** GET /api/v1/bar/orders (bar.orderList) */
export interface BarOrderListQuery {
  status?: E.OrderStatus;
  payment_status?: E.PaymentStatus;
  bar_table_id?: Uuid;
  bar_tab_id?: Uuid;
  member_id?: Uuid; // staff only
  from?: IsoDate;
  to?: IsoDate;
}

/** POST /api/v1/bar/orders/:id/cancel (bar.orderCancel) */
export interface BarOrderCancelRequest {
  reason: string;
}

/** POST /api/v1/bar/tabs (bar.tabOpen) */
export interface BarTabOpenRequest {
  bar_table_id?: Uuid;
  member_id?: Uuid; // Staff only: book/order on behalf of this member. MEMBER callers: omit (implied = self).
  guest_name?: string; // required when no member_id
}

/** GET /api/v1/bar/tabs (bar.tabList) */
export interface BarTabListQuery {
  status?: E.TabStatus;
  member_id?: Uuid; // staff only
  from?: IsoDate;
  to?: IsoDate;
}

/** POST /api/v1/bar/tabs/:id/settle (bar.tabSettle) */
export interface BarTabSettleRequest {
  payment_method: E.PaymentMethod; // CASH | CARD | UPI
}

/** GET /api/v1/bar/daily-summary (bar.dailySummary) */
export interface BarDailySummaryQuery {
  date?: IsoDate; // default today (IST)
}

/** GET /api/v1/kitchen/orders (kitchen.list) */
export interface KitchenListQuery {
  status?: E.OrderStatus[]; // default NEW,ACCEPTED,PREPARING,READY
  date?: IsoDate; // default today
}

/** PATCH /api/v1/kitchen/orders/:id/status (kitchen.status) */
export interface KitchenStatusRequest {
  status: E.OrderStatus; // next status per ORDER_TRANSITIONS
  note?: string; // required when status = CANCELLED (reason)
}

/** POST /api/v1/enquiries (enquiries.create) */
export interface EnquiriesCreateRequest {
  name: string;
  phone: string;
  email?: string;
  enquiry_type?: E.EnquiryType; // default GENERAL
  message?: string;
  membership_plan_id?: Uuid;
  sport_type?: E.SportType; // TRIAL
  preferred_start_at?: IsoDateTime; // TRIAL: must be in the future
  source?: E.EnquirySource; // staff only: PHONE | WALK_IN
}

/** GET /api/v1/enquiries/summary (enquiries.summary) */
export interface EnquiriesSummaryQuery {
  from?: IsoDate;
  to?: IsoDate;
}

/** GET /api/v1/enquiries (enquiries.list) */
export interface EnquiriesListQuery {
  status?: E.EnquiryStatus;
  enquiry_type?: E.EnquiryType;
  source?: E.EnquirySource;
  assigned_to_user_id?: Uuid;
  follow_up_due?: boolean; // next_follow_up_at <= now and status open
  q?: string;
}

/** PATCH /api/v1/enquiries/:id (enquiries.update) */
export interface EnquiriesUpdateRequest {
  status?: E.EnquiryStatus; // per ENQUIRY_TRANSITIONS; not CONVERTED
  assigned_to_user_id?: Uuid;
  next_follow_up_at?: IsoDateTime;
  lost_reason?: string; // required when status = LOST
  name?: string;
  phone?: string;
  email?: string;
  message?: string;
}

/** POST /api/v1/enquiries/:id/follow-ups (enquiries.followUp) */
export interface EnquiriesFollowUpRequest {
  method: E.FollowUpMethod;
  note: string;
  next_follow_up_at?: IsoDateTime;
  new_status?: E.EnquiryStatus; // default: NEW -> CONTACTED
}

/** POST /api/v1/enquiries/:id/quotes (enquiries.quoteCreate) */
export interface EnquiriesQuoteCreateRequest {
  membership_plan_id?: Uuid;
  description: string;
  amount: Money;
  valid_until: IsoDate;
  send_now?: boolean; // true => status SENT and enquiry -> QUOTE_SENT
}

/** PATCH /api/v1/quotes/:id (enquiries.quoteUpdate) */
export interface EnquiriesQuoteUpdateRequest {
  status: E.QuoteStatus;
}

/** POST /api/v1/enquiries/:id/trial-booking (enquiries.trialBooking) */
export interface EnquiriesTrialBookingRequest {
  court_id: Uuid;
  start_at: IsoDateTime;
}

/** POST /api/v1/enquiries/:id/convert (enquiries.convert) */
export interface EnquiriesConvertRequest {
  email?: string; // required if the enquiry has no email
  date_of_birth?: IsoDate;
  address?: string;
  initial_password?: string;
  membership_plan_id: Uuid;
  payment_method: E.PaymentMethod;
}

/** GET /api/v1/business-clients (clients.list) */
export interface ClientsListQuery {
  q?: string;
  is_active?: boolean;
}

/** POST /api/v1/business-clients (clients.create) */
export interface ClientsCreateRequest {
  company_name: string;
  contact_name: string;
  email: string;
  phone?: string;
  gstin?: string; // 15-char GSTIN
  billing_address?: string;
  notes?: string;
  create_login?: boolean; // true => creates users(role BUSINESS_CLIENT)
  initial_password?: string; // required when create_login = true
}

/** PATCH /api/v1/business-clients/:id (clients.update) */
export interface ClientsUpdateRequest {
  company_name?: string;
  contact_name?: string;
  email?: string;
  phone?: string;
  gstin?: string;
  billing_address?: string;
  notes?: string;
  is_active?: boolean;
}

/** GET /api/v1/invoices (invoices.list) */
export interface InvoicesListQuery {
  status?: E.InvoiceStatus;
  invoice_type?: E.InvoiceType;
  business_client_id?: Uuid; // OWNER_ADMIN only
  member_id?: Uuid; // OWNER_ADMIN only
  from?: IsoDate;
  to?: IsoDate;
  overdue?: boolean;
}

/** POST /api/v1/invoices (invoices.create) */
export interface InvoicesCreateRequest {
  invoice_type: E.InvoiceType;
  business_client_id?: Uuid; // required for BUSINESS
  member_id?: Uuid; // required for MEMBERSHIP
  issue_date?: IsoDate; // default today
  due_date: IsoDate; // >= issue_date
  items: { description: string; quantity: number; unit_price: Money }[]; // >=1 line
  tax_rate?: Percent; // default setting tax_rate_business
  notes?: string;
  send_now?: boolean;
}

/** PATCH /api/v1/invoices/:id (invoices.update) */
export interface InvoicesUpdateRequest {
  due_date?: IsoDate;
  items?: { description: string; quantity: number; unit_price: Money }[]; // replaces all lines
  tax_rate?: Percent;
  notes?: string;
}

/** POST /api/v1/payments (payments.create) */
export interface PaymentsCreateRequest {
  source_type: E.PaymentSourceType;
  source_id: Uuid;
  amount?: Money; // default = remaining due. Partial payments allowed ONLY for INVOICE; every other source must equal the full amount due
  payment_method: E.PaymentMethod; // MEMBER / BUSINESS_CLIENT: ONLINE only. FRONT_DESK: CASH | CARD | UPI. OWNER_ADMIN: any
  gateway_reference?: string;
  notes?: string;
}

/** GET /api/v1/payments (payments.list) */
export interface PaymentsListQuery {
  source_type?: E.PaymentSourceType;
  revenue_category?: E.RevenueCategory;
  method?: E.PaymentMethod;
  status?: E.PaymentTxnStatus;
  member_id?: Uuid; // OWNER_ADMIN only
  business_client_id?: Uuid; // OWNER_ADMIN only
  from?: IsoDate;
  to?: IsoDate;
}

/** POST /api/v1/payments/:id/refund (payments.refund) */
export interface PaymentsRefundRequest {
  amount: Money; // > 0, <= amount - refunded_amount
  reason: string;
}

/** GET /api/v1/staff (staff.list) */
export interface StaffListQuery {
  q?: string;
  role?: E.UserRole;
  is_active?: boolean;
}

/** POST /api/v1/staff (staff.create) */
export interface StaffCreateRequest {
  full_name: string;
  email: string;
  phone?: string;
  role: E.UserRole; // FRONT_DESK | KITCHEN_MANAGER | OWNER_ADMIN only
  password: string;
  designation: string;
  default_area?: E.ShiftArea;
  monthly_salary: Money;
  joined_on?: IsoDate;
}

/** PATCH /api/v1/staff/:id (staff.update) */
export interface StaffUpdateRequest {
  full_name?: string;
  phone?: string;
  designation?: string;
  default_area?: E.ShiftArea;
  monthly_salary?: Money;
  is_active?: boolean;
}

/** GET /api/v1/staff/shifts (staff.shifts) */
export interface StaffShiftsQuery {
  from: IsoDate;
  to: IsoDate; // max 31 days
  staff_id?: Uuid;
  area?: E.ShiftArea;
}

/** POST /api/v1/staff/shifts (staff.shiftCreate) */
export interface StaffShiftCreateRequest {
  staff_id: Uuid;
  shift_date: IsoDate;
  start_time: TimeOfDay;
  end_time: TimeOfDay; // > start_time (same day)
  area: E.ShiftArea;
  notes?: string;
}

/** PATCH /api/v1/staff/shifts/:id (staff.shiftUpdate) */
export interface StaffShiftUpdateRequest {
  shift_date?: IsoDate;
  start_time?: TimeOfDay;
  end_time?: TimeOfDay;
  area?: E.ShiftArea;
  notes?: string;
}

/** GET /api/v1/staff/leave-requests (staff.leaveList) */
export interface StaffLeaveListQuery {
  status?: E.LeaveStatus;
  staff_id?: Uuid; // OWNER_ADMIN only
  from?: IsoDate;
  to?: IsoDate;
}

/** POST /api/v1/staff/leave-requests (staff.leaveCreate) */
export interface StaffLeaveCreateRequest {
  leave_type: E.LeaveType;
  start_date: IsoDate;
  end_date: IsoDate; // >= start_date
  reason?: string;
}

/** POST /api/v1/staff/leave-requests/:id/decision (staff.leaveDecide) */
export interface StaffLeaveDecideRequest {
  decision: E.LeaveDecision;
  note?: string; // required when REJECT
}

/** GET /api/v1/staff/payroll (staff.payrollList) */
export interface StaffPayrollListQuery {
  staff_id?: Uuid; // OWNER_ADMIN only
  pay_period?: IsoDate; // first day of month
  status?: E.PayrollStatus;
}

/** POST /api/v1/staff/payroll (staff.payrollCreate) */
export interface StaffPayrollCreateRequest {
  staff_id: Uuid;
  pay_period: IsoDate; // first day of month
  amount?: Money; // default staff.monthly_salary
  payment_method: E.PaymentMethod;
  mark_paid?: boolean;
  notes?: string;
}

/** POST /api/v1/staff/payroll/:id/pay (staff.payrollPay) */
export interface StaffPayrollPayRequest {
  payment_method?: E.PaymentMethod;
  paid_on?: IsoDate; // default today
}

/** GET /api/v1/reports/dashboard (reports.dashboard) */
export interface ReportsDashboardQuery {
  period: E.ReportPeriod; // TODAY = IST today; WEEK = Monday..today; MONTH = 1st..today
}

/** GET /api/v1/reports/revenue (reports.revenue) */
export interface ReportsRevenueQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
  group_by?: E.ReportGroupBy; // default CATEGORY
}

/** GET /api/v1/reports/courts (reports.courts) */
export interface ReportsCourtsQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/reports/memberships (reports.memberships) */
export interface ReportsMembershipsQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/reports/shop (reports.shop) */
export interface ReportsShopQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/reports/bar (reports.bar) */
export interface ReportsBarQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/reports/finance (reports.finance) */
export interface ReportsFinanceQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/reports/tax (reports.tax) */
export interface ReportsTaxQuery {
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/reports/export (reports.export) */
export interface ReportsExportQuery {
  report: E.ExportReport;
  from: IsoDate; // Inclusive IST business date.
  to: IsoDate; // Inclusive IST business date; to >= from; max 366 days.
}

/** GET /api/v1/notifications (notifications.list) */
export interface NotificationsListQuery {
  unread_only?: boolean;
}

/** PATCH /api/v1/settings/:key (settings.update) */
export interface SettingsUpdateRequest {
  value: string; // JSON scalar matching the existing value's type (string | number | boolean)
}

