// Generates every doc/contract file that is DERIVED from a source of truth. Run: npm run docs:build
//   sources:  tools/api/endpoints.mjs  tools/api/requirements.mjs  tools/api/examples.mjs  tools/api/ownership.mjs
//             database/migrations/*.sql   shared/constants/*.ts   shared/types/*.ts   mock-data/*.json
//   outputs:  see OUTPUTS at the bottom. Generated files carry a banner: DO NOT EDIT BY HAND.
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import { ROOT, parseSchema, readMigrations } from './lib/schema.mjs';
import { parseTypes, tsToSchema, enumConstFromType, pascal, makeSampler, interfaceForTable, sampleUuid } from './lib/ts-types.mjs';
import { endpoints, PUB, roleName, isOwnOnly, ALL_ROLES, ruleRefs } from './api/endpoints.mjs';
import { FR, NFR, UR, BR, COVERAGE, MODULES } from './api/requirements.mjs';
import { examples } from './api/examples.mjs';
import { DEVS, MODULE_OWNER, MODULE_TITLE, TABLE_OWNER, TABLE_PURPOSE } from './api/ownership.mjs';
import * as ENUMS from '../shared/constants/enums.ts';
import { ERROR_CODES } from '../shared/constants/errors.ts';
import { API_PREFIX } from '../shared/constants/rules.ts';

const schema = parseSchema();
const { interfaces, aliases } = parseTypes(['types/rows.ts', 'types/api.ts']);
const mockCache = {};
const mockRows = (t) => (mockCache[t] ??= JSON.parse(readFileSync(path.join(ROOT, 'mock-data', t.replace(/_/g, '-') + '.json'), 'utf8')));
const FK_TABLE = {};
const sampler = makeSampler({ interfaces, aliases, enums: ENUMS, mockRow: (t) => mockRows(t)[0], idFor: (f) => (FK_TABLE[f] ? mockRows(FK_TABLE[f])[0].id : null) });
for (const t of Object.keys(schema.tables)) sampler.register(interfaceForTable(t), t);
for (const t of Object.values(schema.tables)) for (const c of t.columns) if (c.references) FK_TABLE[c.name] = c.references;
const out = (rel, content) => { const p = path.join(ROOT, rel); mkdirSync(path.dirname(p), { recursive: true }); writeFileSync(p, content); };
const BANNER_MD = (src) => `<!-- GENERATED by tools/gen-docs.mjs from ${src} — DO NOT EDIT BY HAND. Change the source, run \`npm run docs:build\`. -->\n\n`;
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const ROLE_LABEL = { MEMBER: 'Member', FRONT_DESK: 'Front Desk', KITCHEN_MANAGER: 'Kitchen', BUSINESS_CLIENT: 'Business Client', OWNER_ADMIN: 'Owner/Admin', PUBLIC: 'Public (no login)' };
const fullPath = (p) => API_PREFIX + p;
const modOrder = Object.keys(MODULE_TITLE);

// ---------------------------------------------------------------- derived endpoint facts
const frIds = new Set(FR.map((r) => r[0]));
for (const e of endpoints) for (const r of e.reqs) if (!frIds.has(r)) throw new Error(`${e.id}: unknown requirement ${r}`);
const parseRes = (r) => { let m; if ((m = r.match(/^Page<(\w+)>$/))) return { kind: 'page', type: m[1] }; if ((m = r.match(/^(\w+)\[\]$/))) return { kind: 'array', type: m[1] }; if (r === 'void') return { kind: 'void' }; return { kind: 'one', type: r }; };
const epErrors = (e) => {
  const codes = [];
  const add = (c) => { if (!codes.includes(c)) codes.push(c); };
  if (!e.roles.includes(PUB) || e.roles.length > 1 && e.roles.includes(PUB) && false) { /* auth required for non-public */ }
  if (!(e.roles.length === 1 && e.roles[0] === PUB)) add('AUTH_UNAUTHORIZED');
  if (e.body.length || e.query.length || e.path?.includes(':')) add('VALIDATION_ERROR');
  if (!(e.roles.length === 1 && e.roles[0] === PUB) && e.roles.filter((r) => r !== PUB).length < 5) add('FORBIDDEN');
  for (const c of e.errors) { if (!ERROR_CODES[c]) throw new Error(`${e.id}: unknown error code ${c}`); add(c); }
  if (e.path.includes(':') && !e.errors.some((c) => /NOT_FOUND$/.test(c))) add('NOT_FOUND');
  return codes;
};
const rolesText = (e) => e.roles.map((r) => (r === PUB ? 'PUBLIC' : roleName(r) + (isOwnOnly(r) ? ' (own only)' : ''))).join(', ');

// ================================================================== A. requests.generated.ts
const tsType = (f) => {
  const t = f.type;
  if (t === 'object[]') return `{ ${f.of.map((x) => `${x.name}${x.required ? '' : '?'}: ${tsType(x)}`).join('; ')} }[]`;
  if (t.startsWith('array:enum:')) return `E.${pascal(t.slice(11).toLowerCase().replace(/_/g, '-'))}[]`;
  if (t.startsWith('array:')) return `${tsType({ type: t.slice(6) })}[]`;
  if (t.startsWith('enum:')) return `E.${pascal(t.slice(5).toLowerCase().replace(/_/g, '-'))}`;
  return { uuid: 'Uuid', string: 'string', text: 'string', email: 'string', phone: 'string', url: 'string', int: 'number', number: 'number', money: 'Money', percent: 'Percent', bool: 'boolean', date: 'IsoDate', datetime: 'IsoDateTime', time: 'TimeOfDay' }[t] ?? (() => { throw new Error('unknown field type ' + t); })();
};
{
  let ts = `/**\n * GENERATED by tools/gen-docs.mjs from tools/api/endpoints.mjs — DO NOT EDIT BY HAND.\n * One interface per endpoint body (…Request) / query string (…Query). Frontend sends these; backend validates against them.\n * Query-string values arrive as strings on the wire and are coerced by the validator to the types below.\n */\nimport type * as E from '../constants/enums';\nimport type { Uuid, Money, Percent, IsoDate, IsoDateTime, TimeOfDay } from './rows';\n\n`;
  for (const e of endpoints) {
    for (const [kind, fields] of [['Request', e.body], ['Query', e.query]]) {
      if (!fields.length) continue;
      ts += `/** ${e.method} ${fullPath(e.path)} (${e.id}) */\nexport interface ${pascal(e.id)}${kind} {\n`;
      for (const f of fields) ts += `  ${f.name}${f.required ? '' : '?'}: ${tsType(f)};${f.rule ? ' // ' + f.rule.replace(/\n/g, ' ') : ''}\n`;
      ts += '}\n\n';
    }
  }
  out('shared/types/requests.generated.ts', ts);
}

// ---------------------------------------------------------------- generated examples (types + seed rows)
const FIELD_HINTS = [[/email/, 'visitor@example.com'], [/phone/, '+919811100001'], [/(^|_)name$|^label$/, 'Aarav Kapoor'], [/^sku$/, 'RKT-WIL-CLASH100'], [/address/, '12, Lake View Residency, Baner, Pune 411045'], [/^password|current_password|new_password/, 'Password@123'], [/title/, 'Friday Social Doubles'], [/^key$/, 'club_name'], [/^gstin/, '27AABCT1234F1Z5']];
function sampleField(f) {
  const t = f.type;
  if (t === 'object[]') return [Object.fromEntries(f.of.filter((x) => x.required).map((x) => [x.name, sampleField(x)]))];
  if (t.startsWith('array:enum:')) return [Object.values(ENUMS[t.slice(11)])[0]];
  if (t.startsWith('array:')) return ['item'];
  if (t.startsWith('enum:')) { const vals = Object.values(ENUMS[t.slice(5)]); const firstMentioned = vals.map((v) => [v, (f.rule ?? '').search(new RegExp(`\\b${v}\\b`))]).filter(([, i]) => i >= 0).sort((a, b) => a[1] - b[1])[0]; return firstMentioned ? firstMentioned[0] : vals[0]; }
  switch (t) {
    case 'uuid': return FK_TABLE[f.name] ? mockRows(FK_TABLE[f.name])[0].id : sampleUuid(f.name);
    case 'money': return '100.00'; case 'percent': return '10.00'; case 'int': return 1; case 'number': return 1; case 'bool': return true;
    case 'date': return '2026-10-10'; case 'datetime': return '2026-10-10T12:30:00.000Z'; case 'time': return '18:00:00';
    case 'url': return 'https://example.com/image.jpg'; case 'text': return 'Sample text';
    default: return (FIELD_HINTS.find(([re]) => re.test(f.name)) ?? [, 'string'])[1];
  }
}
function generatedExample(e) {
  const params = Object.fromEntries([...e.path.matchAll(/:(\w+)/g)].map((m) => [m[1], m[1] === 'key' ? 'club_name' : (mockRows(e.tables[0] ?? 'users')[0]?.id ?? sampleUuid(m[1]))]));
  let url = fullPath(e.path).replace(/:(\w+)/g, (_, p) => params[p]);
  const q = e.query.filter((f) => f.required).map((f) => `${f.name}=${encodeURIComponent(sampleField(f))}`);
  if (q.length) url += '?' + q.join('&');
  const body = e.body.length ? Object.fromEntries(e.body.filter((f) => f.required).map((f) => [f.name, sampleField(f)])) : null;
  const r = parseRes(e.res);
  let response;
  if (e.id === 'reports.export') response = null;
  else if (r.kind === 'void') response = { success: true, data: null };
  else {
    const s = sampler.sampleInterface(r.type);
    response = r.kind === 'page' ? { success: true, data: [s], meta: { page: 1, page_size: 20, total: 1, total_pages: 1 } } : r.kind === 'array' ? { success: true, data: [s] } : { success: true, data: s };
  }
  return { url, body, response };
}
function generatedError(e) {
  const code = e.errors.find((c) => !/NOT_FOUND$/.test(c)) ?? e.errors[0] ?? (e.body.length || e.query.length ? 'VALIDATION_ERROR' : 'AUTH_UNAUTHORIZED');
  return { status: ERROR_CODES[code].status, body: { success: false, error: { code, message: ERROR_CODES[code].message } } };
}

// ================================================================== B. API_CONTRACT.md
function renderFields(fields, indent = '') {
  let s = `| Field | Type | Required | Rules |\n|---|---|---|---|\n`;
  for (const f of fields) {
    s += `| \`${f.name}\` | ${esc(f.type.replace(/^enum:/, 'enum '))} | ${f.required ? '**yes**' : 'no'} | ${esc(f.rule)} |\n`;
    if (f.of) for (const sub of f.of) s += `| &nbsp;&nbsp;↳ \`${sub.name}\` | ${esc(sub.type)} | ${sub.required ? '**yes**' : 'no'} | ${esc(sub.rule)} |\n`;
  }
  return s;
}
const resText = (e) => {
  if (e.id === 'reports.export') return '`text/csv` file (Content-Disposition: attachment) — NOT the JSON envelope';
  const r = parseRes(e.res);
  if (r.kind === 'page') return `\`data: ${r.type}[]\` + \`meta: PageMeta\``;
  if (r.kind === 'array') return `\`data: ${r.type}[]\``;
  if (r.kind === 'void') return '`data: null`';
  return `\`data: ${r.type}\``;
};
{
  let md = BANNER_MD('tools/api/endpoints.mjs, shared/constants/errors.ts, tools/api/examples.mjs');
  md += `# API Contract — The Champions Club (v1)\n\n> **The single agreement between frontend and backend.** If an endpoint, field or error is not here, it does not exist. To change anything: edit \`tools/api/endpoints.mjs\`, run \`npm run docs:build\`, commit every regenerated file in the SAME pull request, and get the owner of the module (see ownership below) plus one other developer to approve.\n>\n> Machine-readable twin: [openapi.yaml](openapi.yaml) · Request/query TypeScript types: [requests.generated.ts](../../shared/types/requests.generated.ts) · Response types: [rows.ts](../../shared/types/rows.ts), [api.ts](../../shared/types/api.ts) · Errors: [ERROR_CODES.md](../contracts/ERROR_CODES.md) · Permissions: [PERMISSIONS_MATRIX.md](../security/PERMISSIONS_MATRIX.md)\n\n`;
  md += `## 1. Global conventions\n\n| Topic | Rule |\n|---|---|\n`;
  const conv = [
    ['Base URL', '`{API_BASE_URL}/api/v1` — e.g. `http://localhost:4000/api/v1`. Every path below is relative to it.'],
    ['Versioning', 'Version is in the URL (`/api/v1`). Within v1 only **additive, backward-compatible** changes are allowed (new optional field, new endpoint, new enum value announced to the team). Anything breaking (rename, remove, type change, new required field) requires `/api/v2` — see [ADR-012](../decisions/ADR-012-api-versioning.md).'],
    ['Content type', 'Requests and responses are `application/json; charset=utf-8` (except `GET /reports/export` = CSV).'],
    ['Authentication', '`Authorization: Bearer <JWT>` obtained from `/auth/login` or `/auth/signup`. Endpoints marked **PUBLIC** need no token. Token lifetime 8 h; expired/invalid => `401 AUTH_UNAUTHORIZED`.'],
    ['Authorisation', 'Role list per endpoint. `(own only)` = the caller may only touch records that belong to them (member → their `member_id`; business client → their `business_client_id`; staff → their `staff` row). Violations: `403 FORBIDDEN` (or `404` when revealing existence would leak data).'],
    ['Success envelope', '`{ "success": true, "data": <payload>, "message"?: string, "meta"?: PageMeta }`'],
    ['Error envelope', '`{ "success": false, "error": { "code": "<ERROR_CODE>", "message": string, "details"?: object } }` — `code` is always one of [ERROR_CODES.md](../contracts/ERROR_CODES.md). HTTP status is fixed per code. `VALIDATION_ERROR.details.fields` = `{ "<field>": "<message>" }`.'],
    ['Pagination', 'List endpoints marked `Page<T>` accept `?page=1&page_size=20` (default 20, max 100) and return `meta: { page, page_size, total, total_pages }`. Other arrays are unpaginated and bounded.'],
    ['Sorting', 'Fixed per endpoint (documented in the rules). No client-controlled sort in v1.'],
    ['JSON naming', '`snake_case` for every key, identical to DB column names. No camelCase anywhere.'],
    ['IDs', 'UUID v4 strings. Human-readable numbers (`member_code`, `booking_number`, `order_number`, `payment_number`, `invoice_number`) are display fields only — never used as foreign keys.'],
    ['Timestamps', 'UTC ISO-8601 with milliseconds and `Z`: `2026-10-03T12:30:00.000Z`. UI converts to IST (`Asia/Kolkata`) for display.'],
    ['Dates / times', 'Business dates are IST calendar dates `YYYY-MM-DD`; times of day are `HH:mm:ss`. Court `start_at` values must fall on :00 or :30.'],
    ['Money', 'Strings with exactly 2 decimals in INR: `"1250.00"`. Never JSON numbers. All arithmetic via `shared/lib/money.ts`.'],
    ['Null vs absent', 'Responses always include every documented key (`null` when empty), except fields marked optional (`?`) in the TypeScript view types. Requests: omit optional fields; sending `null` clears nullable fields on PATCH.'],
    ['PATCH semantics', 'Partial update: only keys present are changed. Unknown keys => `VALIDATION_ERROR`.'],
    ['Idempotency', 'Payments and order creation accept an optional header `Idempotency-Key: <uuid>`; a repeated key returns the original response (SHOULD, not required for the MVP).'],
    ['Status codes', '200 OK · 201 Created (POST that creates) · 400 VALIDATION_ERROR · 401 · 402 PAYMENT_FAILED · 403 · 404 · 409 conflict/state · 422 business-rule violation · 500.'],
    ['Rate limits', 'Public write endpoints (`POST /enquiries`, `/auth/signup`, `/auth/login`) SHOULD be rate-limited (e.g. 10/min/IP).'],
  ];
  for (const [k, v] of conv) md += `| **${k}** | ${esc(v)} |\n`;
  md += `\n### Standard objects\n\n\`\`\`ts\ninterface PageMeta { page: number; page_size: number; total: number; total_pages: number }\n\`\`\`\n\n`;

  md += `## 2. Endpoint index\n\n| Module | Method | Path | Roles | Operation |\n|---|---|---|---|---|\n`;
  for (const e of endpoints) md += `| ${e.module} | \`${e.method}\` | \`${e.path}\` | ${esc(rolesText(e))} | [${e.id}](#${e.id.replace('.', '')}) |\n`;
  md += `\n**${endpoints.length} endpoints** across ${new Set(endpoints.map((e) => e.module)).size} modules.\n\n`;

  md += `## 3. Module ownership\n\n| Module | Owner | Base path(s) |\n|---|---|---|\n`;
  for (const m of modOrder) {
    const eps = endpoints.filter((e) => e.module === m); if (!eps.length) continue;
    const bases = [...new Set(eps.map((e) => '/' + e.path.split('/')[1]))].join(', ');
    md += `| ${MODULE_TITLE[m]} (\`${m}\`) | ${DEVS[MODULE_OWNER[m]].name} — ${DEVS[MODULE_OWNER[m]].title} | ${bases} |\n`;
  }
  md += `\n## 4. Endpoints\n`;
  for (const m of modOrder) {
    const eps = endpoints.filter((e) => e.module === m); if (!eps.length) continue;
    md += `\n---\n\n### Module: ${MODULE_TITLE[m]}\n\n*Owner: ${DEVS[MODULE_OWNER[m]].name} (${DEVS[MODULE_OWNER[m]].title})*\n`;
    for (const e of eps) {
      const errs = epErrors(e);
      md += `\n<a id="${e.id.replace('.', '')}"></a>\n#### \`${e.method} ${fullPath(e.path)}\` — ${e.id}\n\n${e.summary}\n\n`;
      md += `| | |\n|---|---|\n| **Auth** | ${e.roles.length === 1 && e.roles[0] === PUB ? 'None (PUBLIC)' : e.roles.includes(PUB) ? 'Optional for PUBLIC callers; staff send Bearer JWT' : 'Bearer JWT'} |\n| **Roles** | ${rolesText(e)} |\n| **Success** | ${e.status} · ${resText(e)} |\n| **Requirements** | ${e.reqs.join(', ') || '—'} |\n| **Governing rules** | ${(ruleRefs[e.id] ?? []).map((r) => `[${r}](../business-rules/BUSINESS_RULES.md)`).join(', ') || '—'} |\n| **Tables touched** | ${e.tables.map((t) => '`' + t + '`').join(', ') || '—'} |\n`;
      const pathParams = [...e.path.matchAll(/:(\w+)/g)].map((x) => x[1]);
      if (pathParams.length) md += `| **Path params** | ${pathParams.map((p) => `\`${p}\` (uuid${p === 'key' ? '→ setting key' : ''})`).join(', ')} |\n`;
      if (e.query.length || /^Page</.test(e.res)) md += `\n**Query parameters**\n\n${renderFields([...e.query, ...(/^Page</.test(e.res) ? [{ name: 'page', type: 'int', required: false, rule: 'default 1' }, { name: 'page_size', type: 'int', required: false, rule: 'default 20, max 100' }] : [])])}`;
      if (e.body.length) md += `\n**Request body** — type \`${pascal(e.id)}Request\`\n\n${renderFields(e.body)}`;
      if (e.rules) md += `\n**Rules / behaviour:** ${e.rules}\n`;
      md += `\n**Errors**\n\n| Code | HTTP | Meaning here |\n|---|---|---|\n`;
      for (const c of errs) md += `| \`${c}\` | ${ERROR_CODES[c].status} | ${esc(ERROR_CODES[c].message)} |\n`;
      const hand = examples[e.id] ?? [];
      for (const ex of hand) {
        md += `\n**Example — ${ex.title}**${ex.status ? ` (HTTP ${ex.status})` : ''}\n\n`;
        const q = ex.request?.query;
        const body = q ? null : ex.request;
        md += `\`\`\`http\n${e.method} ${fullPath(e.path)}${q ?? ''}\n\`\`\`\n`;
        if (body && Object.keys(body).length) md += `\n\`\`\`json\n${JSON.stringify(body, null, 2)}\n\`\`\`\n`;
        md += `\n\`\`\`json\n${JSON.stringify(ex.response, null, 2)}\n\`\`\`\n`;
      }
      if (!hand.some((x) => !x.status)) {
        const gx = generatedExample(e);
        md += `\n**Example (generated from the types and seed data — shape is exact, values illustrative)**\n\n\`\`\`http\n${e.method} ${gx.url}\n\`\`\`\n`;
        if (gx.body) md += `\n\`\`\`json\n${JSON.stringify(gx.body, null, 2)}\n\`\`\`\n`;
        md += gx.response ? `\n\`\`\`json\n${JSON.stringify(gx.response, null, 2)}\n\`\`\`\n` : `\n\`\`\`csv\ndate,category,method,amount,tax_amount\n2026-10-03,COURT,UPI,800.00,122.03\n\`\`\`\n`;
      }
      if (!hand.some((x) => x.status)) {
        const ge = generatedError(e);
        md += `\n**Example error (HTTP ${ge.status})**\n\n\`\`\`json\n${JSON.stringify(ge.body, null, 2)}\n\`\`\`\n`;
      }
    }
  }
  out('docs/api/API_CONTRACT.md', md);
}

// ================================================================== C. openapi.yaml
const known = new Set(Object.keys(interfaces));
function interfaceSchema(name, seen = new Set()) {
  const it = interfaces[name];
  const own = { type: 'object', properties: Object.fromEntries(it.fields.map((f) => [f.name, tsToSchema(f.type, known, aliases)])), required: it.fields.filter((f) => !f.optional).map((f) => f.name) };
  if (!own.required.length) delete own.required;
  return it.extends.length ? { allOf: [...it.extends.map((p) => ({ $ref: `#/components/schemas/${p}` })), own] } : own;
}
const schemas = { PageMeta: tsToSchema('{ page: number; page_size: number; total: number; total_pages: number }', known), ApiError: { type: 'object', required: ['success', 'error'], properties: { success: { type: 'boolean', enum: [false] }, error: { type: 'object', required: ['code', 'message'], properties: { code: { type: 'string', enum: Object.keys(ERROR_CODES) }, message: { type: 'string' }, details: { type: 'object', additionalProperties: true } } } } } };
for (const n of Object.keys(interfaces)) schemas[n] = interfaceSchema(n);
// type aliases that are objects (UserPublic = Omit<User,'password_hash'>)
for (const [n, t] of Object.entries(aliases)) { const m = t.match(/^Omit<(\w+), '([^']+)'>$/); if (m && interfaces[m[1]]) { const base = interfaceSchema(m[1]); delete base.properties?.[m[2]]; base.required = base.required?.filter((x) => x !== m[2]); schemas[n] = base; known.add(n); } }
const withRequired = (obj, names) => (names.length ? { ...obj, required: names } : obj);
const fieldSchema = (f) => {
  const t = f.type; let s;
  if (t === 'object[]') s = { type: 'array', items: withRequired({ type: 'object', properties: Object.fromEntries(f.of.map((x) => [x.name, fieldSchema(x)])) }, f.of.filter((x) => x.required).map((x) => x.name)) };
  else if (t.startsWith('array:enum:')) s = { type: 'array', items: { type: 'string', enum: Object.values(ENUMS[t.slice(11)]) } };
  else if (t.startsWith('array:')) s = { type: 'array', items: fieldSchema({ type: t.slice(6) }) };
  else if (t.startsWith('enum:')) s = { type: 'string', enum: Object.values(ENUMS[t.slice(5)]) };
  else s = { uuid: { type: 'string', format: 'uuid' }, string: { type: 'string' }, text: { type: 'string' }, email: { type: 'string', format: 'email' }, phone: { type: 'string' }, url: { type: 'string', format: 'uri' }, int: { type: 'integer' }, number: { type: 'number' }, money: { type: 'string', pattern: '^\\d+\\.\\d{2}$' }, percent: { type: 'string', pattern: '^\\d+(\\.\\d{1,2})?$' }, bool: { type: 'boolean' }, date: { type: 'string', format: 'date' }, datetime: { type: 'string', format: 'date-time' }, time: { type: 'string', pattern: '^\\d{2}:\\d{2}(:\\d{2})?$' } }[t];
  if (f.rule && s) s = { ...s, description: f.rule };
  return s;
};
const okSchema = (e) => {
  if (e.id === 'reports.export') return null;
  const r = parseRes(e.res);
  const ref = (n) => (known.has(n) ? { $ref: `#/components/schemas/${n}` } : {});
  const env = (data, extra = {}) => ({ type: 'object', required: ['success', 'data'], properties: { success: { type: 'boolean', enum: [true] }, data, message: { type: 'string' }, ...extra } });
  if (r.kind === 'page') return env({ type: 'array', items: ref(r.type) }, { meta: { $ref: '#/components/schemas/PageMeta' } });
  if (r.kind === 'array') return env({ type: 'array', items: ref(r.type) });
  if (r.kind === 'void') return env({ nullable: true });
  return env(ref(r.type));
};
{
  const paths = {};
  for (const e of endpoints) {
    const p = e.path.replace(/:(\w+)/g, '{$1}');
    const op = { operationId: e.id, tags: [MODULE_TITLE[e.module]], summary: e.summary, description: [e.rules, `Requirements: ${e.reqs.join(', ')}`].filter(Boolean).join('\n\n'), 'x-roles': e.roles.map((r) => (r === PUB ? 'PUBLIC' : r)), 'x-owner': DEVS[MODULE_OWNER[e.module]].name, 'x-requirements': e.reqs, 'x-tables': e.tables };
    op.security = e.roles.length === 1 && e.roles[0] === PUB ? [] : [{ bearerAuth: [] }];
    const params = [...e.path.matchAll(/:(\w+)/g)].map((m) => ({ name: m[1], in: 'path', required: true, schema: m[1] === 'key' ? { type: 'string' } : { type: 'string', format: 'uuid' } }));
    for (const q of e.query) params.push({ name: q.name, in: 'query', required: q.required, description: q.rule || undefined, schema: fieldSchema({ ...q, rule: '' }) });
    if (/^Page</.test(e.res)) params.push({ name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, { name: 'page_size', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } });
    if (params.length) op.parameters = params;
    if (e.body.length) op.requestBody = { required: e.body.some((b) => b.required), content: { 'application/json': { schema: withRequired({ type: 'object', properties: Object.fromEntries(e.body.map((b) => [b.name, fieldSchema(b)])) }, e.body.filter((b) => b.required).map((b) => b.name)) } } };
    const ok = okSchema(e);
    op.responses = { [e.status]: ok ? { description: 'Success', content: { 'application/json': { schema: ok } } } : { description: 'CSV download', content: { 'text/csv': { schema: { type: 'string' } } } } };
    const byStatus = {};
    for (const c of epErrors(e)) (byStatus[ERROR_CODES[c].status] ??= []).push(c);
    for (const [st, codes] of Object.entries(byStatus)) op.responses[st] = { description: codes.join(' | '), content: { 'application/json': { schema: { $ref: '#/components/schemas/ApiError' } } } };
    (paths[p] ??= {})[e.method.toLowerCase()] = op;
  }
  const doc = { openapi: '3.0.3', info: { title: 'The Champions Club API', version: '1.0.0', description: 'GENERATED from tools/api/endpoints.mjs — DO NOT EDIT BY HAND. Human-readable version: API_CONTRACT.md. Schemas are derived from shared/types/*.ts (TypeScript is authoritative; inline/complex shapes may appear as free-form).' }, servers: [{ url: '/api/v1' }], components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } }, schemas }, paths };
  out('docs/api/openapi.yaml', `# GENERATED by tools/gen-docs.mjs — DO NOT EDIT BY HAND\n` + YAML.stringify(doc, { lineWidth: 0 }));
}

// ================================================================== D. REQUIREMENTS + TRACEABILITY
const epsByReq = {};
for (const e of endpoints) for (const r of e.reqs) (epsByReq[r] ??= []).push(e);
const modKey = (id) => id.split('-')[1];
const reqTables = (id) => [...new Set((epsByReq[id] ?? []).flatMap((e) => e.tables))];
const reqApis = (id) => [...new Set((epsByReq[id] ?? []).map((e) => `${e.method} ${e.path}`))];
const PRI_ORDER = { MUST: 0, SHOULD: 1, NICE: 2 };
{
  let md = BANNER_MD('tools/api/requirements.mjs, tools/api/endpoints.mjs');
  md += `# Requirements — The Champions Club\n\nPrimary source of truth: *Sports Club Management System* (problem statement). Nothing was invented beyond it without being recorded in [ASSUMPTIONS.md](../ASSUMPTIONS.md). Every requirement has a unique ID used in code comments, tests, PRs and the [traceability matrix](TRACEABILITY_MATRIX.md).\n\n`;
  md += `**Priority** (nothing is removed — the architecture supports everything; priority only orders the 12-hour build, see [Hackathon plan](#6-hackathon-priority-summary)):\n\n- **MUST** — core of the demo; build first, build properly.\n- **SHOULD** — important; may be simplified (e.g. no PDF, mocked gateway) but the endpoint/table must exist.\n- **NICE** — only if time remains.\n\n`;
  md += `## 1. Functional requirements (FR)\n`;
  for (const [mk, title] of Object.entries(MODULES)) {
    const rows = FR.filter((r) => modKey(r[0]) === mk); if (!rows.length) continue;
    md += `\n### ${mk} — ${title}\n\n| ID | Priority | Actors | Requirement | Problem-statement scene |\n|---|---|---|---|---|\n`;
    for (const [id, pri, actors, text, scene] of rows) md += `| ${id} | ${pri} | ${esc(actors)} | ${esc(text)} | ${esc(scene)} |\n`;
  }
  md += `\n## 2. Non-functional requirements (NFR)\n\n| ID | Priority | Requirement |\n|---|---|---|\n`;
  for (const [id, pri, text] of NFR) md += `| ${id} | ${pri} | ${esc(text)} |\n`;
  md += `\n## 3. User requirements (UR)\n\nWhat each actor needs, expressed as user stories mapped onto the functional requirements that deliver them.\n\n| ID | Priority | Actor | Need | Delivered by |\n|---|---|---|---|---|\n`;
  for (const [id, pri, actor, text, covers] of UR) md += `| ${id} | ${pri} | ${actor} | ${esc(text)} | ${covers.join(', ')} |\n`;
  md += `\n## 4. Business requirements (BR)\n\nWhat the club and owner need from the system.\n\n| ID | Priority | Business need | Delivered by |\n|---|---|---|---|\n`;
  for (const [id, pri, text, covers] of BR) md += `| ${id} | ${pri} | ${esc(text)} | ${covers.join(', ')} |\n`;
  md += `\n## 5. Problem-statement coverage check\n\nEvery capability named in the brief → the requirements that deliver it (verified by \`npm run check\`).\n\n| Capability in the brief | Requirements |\n|---|---|\n`;
  for (const [t, ids] of COVERAGE) md += `| ${esc(t)} | ${ids.join(', ')} |\n`;
  md += `\n## 6. Hackathon priority summary\n\n| Module | MUST | SHOULD | NICE | Total |\n|---|---|---|---|---|\n`;
  let tot = [0, 0, 0];
  for (const [mk, title] of Object.entries(MODULES)) {
    const rows = FR.filter((r) => modKey(r[0]) === mk); const c = ['MUST', 'SHOULD', 'NICE'].map((p) => rows.filter((r) => r[1] === p).length);
    c.forEach((n, i) => (tot[i] += n)); md += `| ${mk} — ${title} | ${c.join(' | ')} | ${rows.length} |\n`;
  }
  md += `| **Total** | **${tot.join('** | **')}** | **${tot.reduce((a, b) => a + b)}** |\n\nSuggested 12-hour sequencing and "what to simplify" per module: see [TEAM_GUIDELINES.md](../integration/TEAM_GUIDELINES.md#12-hour-plan).\n`;
  out('docs/requirements/REQUIREMENTS.md', md);

  let tm = BANNER_MD('tools/api/requirements.mjs, tools/api/endpoints.mjs');
  tm += `# Traceability Matrix\n\nEvery requirement → user(s) → module → API → database entity. API and table columns are **derived** from the \`reqs\` / \`tables\` of each endpoint in [endpoints.mjs](../../tools/api/endpoints.mjs), so they cannot drift. \`UI only\` = delivered by the frontend using other endpoints.\n\n`;
  tm += `## Functional requirements\n\n| Requirement | Pri | User(s) | Module | API | Database entities |\n|---|---|---|---|---|---|\n`;
  for (const r of FR) {
    const [id, pri, actors, , , extra] = r; const apis = reqApis(id); const tbs = reqTables(id);
    tm += `| ${id} | ${pri} | ${esc(actors)} | ${MODULES[modKey(id)]} | ${apis.length ? apis.map((a) => '`' + a + '`').join('<br>') : '*UI only / cross-cutting*'} | ${tbs.length ? tbs.map((t) => '`' + t + '`').join(', ') : '—'} |\n`;
  }
  tm += `\n## User & business requirements (via the FRs that deliver them)\n\n| Requirement | Pri | Delivered by | Modules | Database entities |\n|---|---|---|---|---|\n`;
  for (const [id, pri, , , covers] of UR.map((u) => [u[0], u[1], u[2], u[3], u[4]])) tm += `| ${id} | ${pri} | ${covers.join(', ')} | ${[...new Set(covers.map((c) => MODULES[modKey(c)]))].join(', ')} | ${[...new Set(covers.flatMap(reqTables))].map((t) => '`' + t + '`').join(', ')} |\n`;
  for (const [id, pri, , covers] of BR) tm += `| ${id} | ${pri} | ${covers.join(', ')} | ${[...new Set(covers.map((c) => MODULES[modKey(c)]))].join(', ')} | ${[...new Set(covers.flatMap(reqTables))].map((t) => '`' + t + '`').join(', ')} |\n`;
  tm += `\n## Reverse view: endpoint → requirements\n\n| Endpoint | Requirements |\n|---|---|\n`;
  for (const e of endpoints) tm += `| \`${e.method} ${e.path}\` (${e.id}) | ${e.reqs.join(', ')} |\n`;
  out('docs/requirements/TRACEABILITY_MATRIX.md', tm);
}

// ================================================================== E. PERMISSIONS_MATRIX
{
  const features = [...new Set(endpoints.map((e) => e.feature))];
  const cols = [['MEMBER', 'Member'], ['GUEST', 'Guest (walk-in)'], ['PUBLIC', 'Visitor'], ['FRONT_DESK', 'Front Desk'], ['KITCHEN_MANAGER', 'Kitchen'], ['BUSINESS_CLIENT', 'Business Client'], ['OWNER_ADMIN', 'Owner/Admin']];
  const LETTER = { V: 'View', C: 'Create', U: 'Update', D: 'Delete', A: 'Approve' };
  const cell = (feature, role) => {
    const eps = endpoints.filter((e) => e.feature === feature);
    if (role === 'GUEST') return eps.some((e) => e.guest) ? '*via Front Desk*' : '—';
    const got = {};
    for (const e of eps) for (const r of e.roles) {
      const rn = roleName(r); if (rn !== role) continue;
      const own = isOwnOnly(r); got[e.action] = got[e.action] === false ? false : own ? (got[e.action] ?? true) : false; // false = unrestricted
    }
    // got[action]: true=own only, false=all
    const letters = Object.keys(LETTER).filter((a) => a in got).map((a) => (got[a] === true ? a.toLowerCase() : a));
    return letters.length ? letters.join(' ') : '—';
  };
  let md = BANNER_MD('tools/api/endpoints.mjs');
  md += `# Permissions Matrix\n\nServer-side authorisation rules (R-SEC-01) — enforced by middleware/service checks on **every** endpoint (UI hiding is cosmetic). Derived from the \`roles\` list of each endpoint, so it always matches the API contract.\n\n`;
  md += `**Legend:** \`V\` view · \`C\` create · \`U\` update · \`D\` delete · \`A\` approve. **UPPERCASE = all records**, **lowercase = own records only** (a member's own bookings; a business client's own invoices; a staff member's own shifts/leave/payroll). \`—\` = no access (answer \`403 FORBIDDEN\`). *Guest (walk-in)* has no account — guests are served by Front Desk, who acts on their behalf. *Visitor* = unauthenticated website user. "Create" by a member or business client always acts on their own records (e.g. a member books for themselves; notifications are always the caller's own).\n\n`;
  md += `> Gold / Silver / Junior are NOT roles. All three are \`MEMBER\`; their benefits come from \`membership_plans\` data.\n\n## 1. Feature × role\n\n| Feature | ${cols.map((c) => c[1]).join(' | ')} |\n|---|${cols.map(() => '---').join('|')}|\n`;
  for (const f of features) md += `| ${f} | ${cols.map(([r]) => cell(f, r)).join(' | ')} |\n`;
  md += `\n## 2. Endpoint × role\n\n\`●\` allowed · \`○\` allowed for own records only · blank = forbidden · **PUBLIC** endpoints are open to everyone.\n\n| Endpoint | Operation | Member | Front Desk | Kitchen | Business Client | Owner/Admin |\n|---|---|---|---|---|---|---|\n`;
  for (const e of endpoints) {
    const pub = e.roles.includes(PUB);
    const c = (role) => { if (pub) return e.roles.length === 1 ? '●' : ''; const r = e.roles.find((x) => roleName(x) === role); return r ? (isOwnOnly(r) ? '○' : '●') : ''; };
    const pubAndRoles = pub && e.roles.length > 1;
    md += `| \`${e.method} ${e.path}\` | ${e.id}${pub ? (pubAndRoles ? ' *(public + staff)*' : ' **PUBLIC**') : ''} | ${['MEMBER', 'FRONT_DESK', 'KITCHEN_MANAGER', 'BUSINESS_CLIENT', 'OWNER_ADMIN'].map((role) => (pubAndRoles ? (e.roles.some((x) => roleName(x) === role) ? '●' : '') : c(role))).join(' | ')} |\n`;
  }
  md += `\n## 3. Rules that are not just "role allowed"\n\n| # | Rule | Enforced in |\n|---|---|---|\n`;
  const rules = [
    ['Own-record scoping', 'MEMBER may only read/modify rows whose `member_id` is theirs (bookings, shop orders, bar orders, tabs, payments, memberships, invoices, notifications). Business client: rows whose `business_client_id` is theirs. Staff self-service endpoints: rows whose `staff_id` is theirs.', 'service layer query filter (`WHERE member_id = :caller_member_id`)'],
    ['Kitchen isolation', 'KITCHEN_MANAGER receives the `KitchenOrder` projection only: no prices, totals, discounts, payment data, member contact info.', '`/kitchen/*` returns `KitchenOrder` DTOs; no other bar/finance endpoint allows the role'],
    ['Staff acting for guests', 'FRONT_DESK may create bookings/orders/payments for members and walk-ins; walk-in data is stored as `guest_name` / `guest_phone`.', 'bookings, social, shop, bar, payments services'],
    ['Payment method by role', 'MEMBER and BUSINESS_CLIENT may only pay with `ONLINE`; FRONT_DESK with `CASH`/`CARD`/`UPI`; OWNER_ADMIN any.', '`POST /payments`'],
    ['Refunds', 'Only OWNER_ADMIN refunds manually. Cancellation flows refund automatically by policy.', '`POST /payments/:id/refund`'],
    ['Financial visibility', 'Revenue, tax, payroll, invoices-of-others and reports are OWNER_ADMIN only. FRONT_DESK sees only payments they received (`:own`) and the bar daily summary.', '`/reports/*`, `/payments`, `/staff/payroll`'],
    ['Account creation', 'Only OWNER_ADMIN creates staff, kitchen and business-client accounts; FRONT_DESK registers members; public signup creates MEMBER only.', '`/staff`, `/business-clients`, `/members`, `/auth/signup`'],
    ['Deactivation', 'Setting `users.is_active = false` (via staff/member update) blocks login immediately (`ACCOUNT_DISABLED`).', 'auth middleware'],
    ['Membership plan changes', 'FRONT_DESK may change plans; only OWNER_ADMIN may cancel memberships or edit plan definitions.', '`/memberships/*`'],
    ['Public data minimisation', 'Public availability never reveals who booked; public product data shows `stock_status`, not quantities.', '`/courts/availability`, `/shop/products`'],
  ];
  rules.forEach(([a, b, c], i) => (md += `| ${i + 1} | **${a}** — ${esc(b)} | ${esc(c)} |\n`));
  out('docs/security/PERMISSIONS_MATRIX.md', md);
  const json = Object.fromEntries(endpoints.map((e) => [e.id, { method: e.method, path: fullPath(e.path), roles: e.roles.map((r) => (r === PUB ? 'PUBLIC' : r)) }]));
  out('docs/security/permissions.generated.json', JSON.stringify(json, null, 2) + '\n');
}

// ================================================================== F. DATABASE docs + ER diagram + schema snapshot
{
  const T = schema.tables;
  let er = `%% GENERATED by tools/gen-docs.mjs from database/migrations/*.sql — DO NOT EDIT BY HAND\nerDiagram\n`;
  for (const t of Object.values(T)) {
    for (const fk of t.fks) if (T[fk.table]) er += `  ${fk.table} ||--o{ ${t.name} : "${fk.column}"\n`;
  }
  for (const t of Object.values(T)) {
    er += `  ${t.name} {\n`;
    for (const c of t.columns) if (c.pk || c.references || /^(status|role|.*_type|booking_type)$/.test(c.name) || ['email', 'name', 'full_name', 'start_at', 'end_at', 'amount', 'total_amount', 'price'].includes(c.name))
      er += `    ${c.type.replace(/\[\]/, 'Arr')} ${c.name}${c.pk ? ' PK' : c.references ? ' FK' : ''}\n`;
    er += `  }\n`;
  }
  out('docs/database/er-diagram.mmd', er);

  let md = BANNER_MD('database/migrations/*.sql, tools/api/ownership.mjs');
  md += `# Database Schema — The Champions Club\n\n**ONE canonical PostgreSQL schema.** The migration files in [\`database/migrations\`](../../database/migrations) are the only definition; local PostgreSQL and Supabase PostgreSQL both run those exact files (see [database/README.md](../../database/README.md)). This page is generated from them. A flat snapshot is in [schema.sql](schema.sql) and the diagram in [er-diagram.mmd](er-diagram.mmd).\n\n`;
  md += `## Conventions (mandatory)\n\n| Topic | Rule |\n|---|---|\n`;
  for (const [k, v] of [
    ['Tables', '`snake_case`, **plural**: `members`, `court_bookings`, `shop_orders`.'],
    ['Columns', '`snake_case`: `member_id`, `membership_plan_id`, `created_at`. Never camelCase / PascalCase.'],
    ['Primary key', 'Always `id uuid PRIMARY KEY DEFAULT gen_random_uuid()`.'],
    ['Foreign key', '`<singular_entity>_id` → `<entities>.id` (e.g. `court_id` → `courts.id`). Role-specific FKs keep the entity name with a prefix: `created_by_user_id`, `assigned_to_user_id`, `previous_membership_id`.'],
    ['Enums', 'Postgres enum types named `snake_case` singular (`booking_status`), labels `UPPER_SNAKE_CASE`, identical to [enums.ts](../../shared/constants/enums.ts).'],
    ['Booleans', '`is_*` (`is_active`, `is_read`, `is_public`, `is_available`) or `must_*` (`must_change_password`).'],
    ['Timestamps', '`timestamptz` in UTC. `created_at` / `updated_at` on every mutable table (trigger maintains `updated_at`); event times are `<verb>_at` (`cancelled_at`, `paid_at`).'],
    ['Dates / times', '`date` = IST business date; `time` = IST time of day (shifts only).'],
    ['Money', '`numeric(12,2)` INR, never float. Names: `price`, `unit_price`, `subtotal`, `*_amount`, `*_fee`, `*_rate_per_hour`, `monthly_salary`. Percentages: `numeric(5,2)` named `*_percent` / `tax_rate`.'],
    ['Human numbers', '`member_code`, `booking_number`, `order_number`, `tab_number`, `payment_number`, `invoice_number`, `quote_number`, `employee_code` come from DB sequences via column defaults. Display only; never FK targets.'],
    ['Soft delete', 'No generic `deleted_at` (R-DATA-02). Catalogue rows use `is_active` / `is_available`; financial and operational rows are never deleted (cancel/void/refund states instead).'],
    ['Audit fields', '`created_by_user_id` (and `cancelled_by_user_id`, `decided_by_user_id`, `paid_by_user_id`…) wherever a staff action matters; ledgers (`payments`, `inventory_movements`, `order_status_events`) are append-only by convention.'],
    ['Snapshots', 'Prices, item names and the membership used for a discount are COPIED onto bookings/orders at transaction time so later edits never rewrite history.'],
    ['Security', 'RLS enabled on every table with no policies (migration 0002): only the backend, connecting with `DATABASE_URL`, can access data.'],
  ]) md += `| **${k}** | ${esc(v)} |\n`;
  md += `\n## Design decisions that matter\n\n- **Users vs roles vs memberships.** \`users.role\` (5 values) decides what you can *do*. Gold/Silver/Junior is *data*: \`memberships → membership_plans.membership_type\`. A member without a current membership simply pays walk-in rates.\n- **Membership history is the \`memberships\` table.** Purchase, renewal and plan change each add a row (\`previous_membership_id\` chains them). No separate history table.\n- **Court occupancy has exactly one home: \`court_bookings\`.** Regular, trial, maintenance and the Friday social-session hold are all rows there, so one exclusion constraint guarantees *no two live bookings overlap on a court* (ADR-006). \`social_sessions\` hangs off its SOCIAL_SESSION booking.\n- **One shelf.** \`products.stock_quantity\` is the only stock; \`inventory_movements\` is its ledger; counter and online orders decrement the same row atomically, and \`CHECK (stock_quantity >= 0)\` makes overselling impossible (ADR-007).\n- **Kitchen queue = \`bar_orders\`.** No second table; the kitchen reads a projection. \`order_status_events\` records every transition.\n- **\`payments\` is the revenue ledger.** Every rupee received is a row (\`source_type\` + \`source_id\`, \`revenue_category\`, \`method\`, \`tax_amount\`); refunds update the same row. All finance reports sum this table (ADR-009).\n- **Tax.** Court, membership, shop and bar prices are **tax-inclusive**; \`tax_amount\` is the GST portion. **Invoices are tax-exclusive** (B2B). Rates live in \`club_settings\`.\n- **Settings vs constants.** Owner-editable policy → \`club_settings\`; structural invariants (30-min step, 1-hour session, IST) → \`shared/constants/rules.ts\`.\n\n`;
  md += `## Entity-relationship diagram\n\n\`\`\`mermaid\n${er.split('\n').slice(2).join('\n').replace(/^/, 'erDiagram\n')}\`\`\`\n\n`;
  md += `## Enumerations (${Object.keys(schema.enums).length})\n\n| Postgres type | Values | TypeScript |\n|---|---|---|\n`;
  for (const [n, vals] of Object.entries(schema.enums)) md += `| \`${n}\` | ${vals.map((v) => '`' + v + '`').join(', ')} | \`${n.toUpperCase()}\` |\n`;
  md += `\n## Tables (${Object.keys(T).length})\n\n| Table | Owner | Purpose |\n|---|---|---|\n`;
  for (const t of Object.values(T)) md += `| [\`${t.name}\`](#${t.name}) | ${DEVS[TABLE_OWNER[t.name]].name} | ${esc(TABLE_PURPOSE[t.name])} |\n`;
  for (const t of Object.values(T)) {
    md += `\n### ${t.name}\n\n${TABLE_PURPOSE[t.name]}  \n*Owner: ${DEVS[TABLE_OWNER[t.name]].name}*\n\n| Column | Type | Null | Default | References | Notes |\n|---|---|---|---|---|---|\n`;
    for (const c of t.columns) md += `| \`${c.name}\` | ${esc(c.rawType)} | ${c.notNull ? '' : 'yes'} | ${c.hasDefault ? 'yes' : ''} | ${c.references ? '`' + c.references + '.id`' : ''} | ${esc([c.pk ? 'PK' : '', c.unique ? 'unique' : '', c.description].filter(Boolean).join('; '))} |\n`;
    const idx = schema.indexes.filter((i) => i.table === t.name);
    if (t.constraints.length || idx.length) {
      md += `\n**Constraints & indexes**\n\n`;
      for (const c of t.constraints) md += `- \`${c.replace(/\s+/g, ' ')}\`\n`;
      for (const i of idx) md += `- ${i.unique ? 'UNIQUE ' : ''}INDEX \`${i.name}\` ${esc(i.def)}\n`;
    }
  }
  out('docs/database/DATABASE_SCHEMA.md', md);
  out('docs/database/schema.sql', `-- GENERATED snapshot: concatenation of database/migrations/*.sql in order. DO NOT EDIT — edit/add migrations instead.\n-- Regenerate: npm run docs:build\n\n` + readMigrations().map((m) => `-- ===== ${m.file} =====\n${m.sql}`).join('\n'));
}

// ================================================================== G. ENUMS.md + ERROR_CODES.md
{
  let md = BANNER_MD('shared/constants/enums.ts');
  md += `# Enums & Constants Reference\n\nSource of truth: [shared/constants/enums.ts](../../shared/constants/enums.ts) (values), [rules.ts](../../shared/constants/rules.ts) (invariants, state machines, role routes), [errors.ts](../../shared/constants/errors.ts). **Never redeclare these.** Stored enums are mirrored as Postgres enum types (checked by \`npm run check\`).\n\n`;
  const stored = new Set(Object.keys(schema.enums).map((n) => n.toUpperCase()));
  md += `| Constant | Stored in DB? | Values |\n|---|---|---|\n`;
  for (const [n, v] of Object.entries(ENUMS)) if (typeof v === 'object') md += `| \`${n}\` | ${stored.has(n) ? '`' + n.toLowerCase() + '`' : 'API only'} | ${Object.values(v).map((x) => '`' + x + '`').join(', ')} |\n`;
  md += `\n## State machines\n\nDefined in \`rules.ts\` (\`*_TRANSITIONS\`). The server rejects any other move with \`409 INVALID_STATUS_TRANSITION\` (\`details: { from, to, allowed }\`).\n\n`;
  const T = await import('../shared/constants/rules.ts');
  for (const [name, map] of Object.entries(T).filter(([k]) => k.endsWith('_TRANSITIONS'))) {
    md += `**${name}**\n\n\`\`\`mermaid\nstateDiagram-v2\n`;
    const first = Object.keys(map)[0]; md += `  [*] --> ${first}\n`;
    for (const [from, tos] of Object.entries(map)) for (const to of tos) md += `  ${from} --> ${to}\n`;
    md += `\`\`\`\n\n`;
  }
  out('docs/contracts/ENUMS.md', md);

  let em = BANNER_MD('shared/constants/errors.ts');
  em += `# Error Codes\n\nSource of truth: [shared/constants/errors.ts](../../shared/constants/errors.ts). Every error response is \`{ "success": false, "error": { "code", "message", "details"? } }\` and the HTTP status is **fixed per code** (below). Use these codes — never invent strings. Need a new code? Add it to \`errors.ts\` (team sign-off), run \`npm run docs:build\`.\n\n`;
  const groups = {};
  for (const [k, v] of Object.entries(ERROR_CODES)) (groups[v.group] ??= []).push([k, v]);
  for (const [g, items] of Object.entries(groups)) {
    em += `## ${g}\n\n| Code | HTTP | Default message | Used by |\n|---|---|---|---|\n`;
    for (const [k, v] of items) em += `| \`${k}\` | ${v.status} | ${esc(v.message)} | ${endpoints.filter((e) => epErrors(e).includes(k) && !['VALIDATION_ERROR', 'AUTH_UNAUTHORIZED', 'FORBIDDEN'].includes(k)).map((e) => e.id).join(', ') || (['VALIDATION_ERROR', 'AUTH_UNAUTHORIZED', 'FORBIDDEN', 'INTERNAL_ERROR'].includes(k) ? 'many (automatic)' : '—')} |\n`;
    em += '\n';
  }
  em += `## Conventions\n\n- \`details\` is optional structured context, e.g. \`BOOKING_CONFLICT.details = { court_id, start_at }\`, \`DAILY_BOOKING_LIMIT.details = { plays_used_today, plays_allowed_per_day, date }\`, \`OUT_OF_STOCK.details.items = [{ product_id, requested, available }]\`, \`INVALID_STATUS_TRANSITION.details = { from, to, allowed }\`, \`VALIDATION_ERROR.details.fields = { field: message }\`.\n- DB-level violations are mapped, not leaked: SQLSTATE \`23P01\` (exclusion) → \`BOOKING_CONFLICT\`; \`23514\` on \`products.stock_quantity\` → \`OUT_OF_STOCK\`; \`23505\` on \`users_email_key\` → \`EMAIL_TAKEN\`; \`23505\` on \`memberships_one_active_per_member\` → \`MEMBERSHIP_ALREADY_ACTIVE\`; any unmapped error → \`INTERNAL_ERROR\` (log server-side, return a generic message).\n- Messages are for humans and may be shown in the UI; **logic must branch on \`code\`**, never on \`message\`.\n`;
  out('docs/contracts/ERROR_CODES.md', em);
}

// ================================================================== H. TEAM ownership table (included by TEAM_GUIDELINES via copy)
{
  let md = BANNER_MD('tools/api/ownership.mjs, tools/api/endpoints.mjs');
  md += `# Ownership Map (generated)\n\n| Developer | Focus | API modules | Tables | UI |\n|---|---|---|---|---|\n`;
  for (const [k, d] of Object.entries(DEVS)) {
    const mods = Object.entries(MODULE_OWNER).filter(([, v]) => v === k).map(([m]) => m);
    const tbs = Object.entries(TABLE_OWNER).filter(([, v]) => v === k).map(([t]) => '`' + t + '`');
    md += `| **${d.name}** | ${d.title} | ${mods.map((m) => '`' + m + '`').join(', ')} (${endpoints.filter((e) => mods.includes(e.module)).length} endpoints) | ${tbs.join(', ')} | ${esc(d.ui)} |\n`;
  }
  out('docs/integration/OWNERSHIP_MAP.md', md);
}
// ================================================================== I. extract Mermaid sources (.mmd) from the hand-written docs
{
  const blocks = (md) => [...md.matchAll(/```mermaid\n([\s\S]*?)```/g)].map((m) => ({ code: m[1].trimEnd(), at: m.index }));
  const arch = readFileSync(path.join(ROOT, 'docs/architecture/SYSTEM_ARCHITECTURE.md'), 'utf8');
  out('docs/architecture/system-architecture.mmd', `%% GENERATED from docs/architecture/SYSTEM_ARCHITECTURE.md (first diagram) — DO NOT EDIT BY HAND\n${blocks(arch)[0].code}\n`);
  const flows = readFileSync(path.join(ROOT, 'docs/workflows/USER_FLOWS.md'), 'utf8');
  const heads = [...flows.matchAll(/^## (\d+)\. (.+)$/gm)].map((m) => ({ n: m[1], title: m[2], at: m.index }));
  let mmd = '%% GENERATED from docs/workflows/USER_FLOWS.md — DO NOT EDIT BY HAND. One diagram per block; split on the "%% ===== Flow" markers to render separately.\n';
  for (const b of blocks(flows)) {
    const h = [...heads].reverse().find((x) => x.at < b.at);
    mmd += `\n%% ===== Flow ${h.n}: ${h.title} =====\n${b.code}\n`;
  }
  out('docs/workflows/workflows.mmd', mmd);
}

console.log(`docs generated:${endpoints.length} endpoints, ${FR.length} FR, ${NFR.length} NFR, ${UR.length} UR, ${BR.length} BR, ${Object.keys(schema.tables).length} tables`);
